import type { CodeMappingEntry, LogicCodeStep, StructuredScaffold } from '../types'

export const MINIMUM_WINDOW_SCAFFOLD: StructuredScaffold = {
  methodOpen: 'String minWindow(String s, String t) {',
  methodClose: '}',
  slots: [
    { id: 'target-preparation', label: '准备目标登记', responsibility: '创建 128 项欠账数组和目标索引。', lineCount: 2, conceptIds: ['need-table', 'target-index'] },
    { id: 'target-condition', label: '目标登记条件', responsibility: '目标索引尚未到需求卡末尾时继续。', lineCount: 1, conceptIds: ['target-text', 'target-index', 'target-registration', 'string-length'] },
    { id: 'read-target', label: '读取目标字符', responsibility: '读取目标索引位置的字符编码。', lineCount: 1, conceptIds: ['target-text', 'target-index', 'target-character', 'string-char-at'] },
    { id: 'add-target-debt', label: '增加目标欠账', responsibility: '把当前目标字符的欠账加一。', lineCount: 1, conceptIds: ['target-character', 'need-table', 'target-registration'] },
    { id: 'advance-target', label: '目标索引前进', responsibility: '完成当前目标字符登记后前进一步。', lineCount: 1, conceptIds: ['target-index'] },
    { id: 'window-preparation', label: '准备窗口状态', responsibility: '建立左右边界、总欠账和历史最短记录。', lineCount: 5, conceptIds: ['left-boundary', 'right-boundary', 'missing-count', 'best-window', 'source-text', 'target-text', 'string-length'] },
    { id: 'scan-condition', label: '源串扫描条件', responsibility: '右边界尚未到源字符串末尾时继续。', lineCount: 1, conceptIds: ['source-text', 'right-boundary', 'source-scan', 'string-length'] },
    { id: 'read-incoming', label: '读取入窗字符', responsibility: '读取右边界当前字符编码。', lineCount: 1, conceptIds: ['source-text', 'right-boundary', 'incoming-character', 'string-char-at'] },
    { id: 'incoming-debt-condition', label: '入窗欠账条件', responsibility: '字符余额为正时，它会补齐一项总欠账。', lineCount: 1, conceptIds: ['incoming-character', 'need-table', 'incoming-needed'] },
    { id: 'reduce-missing', label: '减少总欠账', responsibility: '必要字符入窗时把总欠账减一。', lineCount: 1, conceptIds: ['missing-count', 'incoming-needed'] },
    { id: 'debit-incoming', label: '登记字符入窗', responsibility: '无论是否额外，都把入窗字符余额减一。', lineCount: 1, conceptIds: ['incoming-character', 'need-table', 'incoming-debit'] },
    { id: 'shrink-condition', label: '覆盖收缩条件', responsibility: '总欠账为零时继续收缩左侧。', lineCount: 1, conceptIds: ['missing-count', 'window-covered'] },
    { id: 'measure-window', label: '计算当前长度', responsibility: '用右边界减左边界再加一。', lineCount: 1, conceptIds: ['left-boundary', 'right-boundary', 'window-length'] },
    { id: 'shorter-condition', label: '更短窗口条件', responsibility: '当前长度小于历史最短时更新。', lineCount: 1, conceptIds: ['window-length', 'best-window', 'shorter-decision'] },
    { id: 'save-best', label: '保存最短窗口', responsibility: '同时保存当前左边界和窗口长度。', lineCount: 2, conceptIds: ['left-boundary', 'window-length', 'best-window'] },
    { id: 'read-outgoing', label: '读取出窗字符', responsibility: '读取左边界当前字符编码。', lineCount: 1, conceptIds: ['source-text', 'left-boundary', 'outgoing-character', 'string-char-at'] },
    { id: 'credit-outgoing', label: '撤销字符入窗', responsibility: '把出窗字符余额加一。', lineCount: 1, conceptIds: ['outgoing-character', 'need-table', 'outgoing-credit'] },
    { id: 'restored-condition', label: '恢复欠账条件', responsibility: '加回后余额为正时恢复总欠账。', lineCount: 1, conceptIds: ['outgoing-character', 'need-table', 'restored-debt'] },
    { id: 'increase-missing', label: '增加总欠账', responsibility: '失去必要字符时把总欠账加一。', lineCount: 1, conceptIds: ['missing-count', 'restored-debt'] },
    { id: 'advance-left', label: '左边界前进', responsibility: '出窗记账完成后让窗口起点前进一步。', lineCount: 1, conceptIds: ['left-boundary'] },
    { id: 'advance-right', label: '右边界前进', responsibility: '本轮扩张与收缩完成后前进一步。', lineCount: 1, conceptIds: ['right-boundary'] },
    { id: 'no-answer-condition', label: '无答案条件', responsibility: '历史长度仍大于源串长度时说明没有答案。', lineCount: 1, conceptIds: ['source-text', 'best-window', 'no-window-boundary', 'string-length'] },
    { id: 'empty-result', label: '返回空字符串', responsibility: '无答案时截取同一个源串的空片段。', lineCount: 1, conceptIds: ['source-text', 'string-substring', 'method-result', 'no-window-boundary'] },
    { id: 'window-result', label: '返回最短窗口', responsibility: '按历史起点和长度截取源字符串。', lineCount: 1, conceptIds: ['source-text', 'best-window', 'string-substring', 'method-result'] },
  ],
  body: [
    { kind: 'slot', depth: 1, slotId: 'target-preparation', suffix: ';' },
    { kind: 'composite', depth: 1, segments: [{ kind: 'fixed', value: 'while (' }, { kind: 'slot', slotId: 'target-condition' }, { kind: 'fixed', value: ') {' }] },
    { kind: 'slot', depth: 2, slotId: 'read-target', suffix: ';' },
    { kind: 'slot', depth: 2, slotId: 'add-target-debt', suffix: ';' },
    { kind: 'slot', depth: 2, slotId: 'advance-target', suffix: ';' },
    { kind: 'fixed', depth: 1, value: '}' },
    { kind: 'slot', depth: 1, slotId: 'window-preparation', suffix: ';' },
    { kind: 'composite', depth: 1, segments: [{ kind: 'fixed', value: 'while (' }, { kind: 'slot', slotId: 'scan-condition' }, { kind: 'fixed', value: ') {' }] },
    { kind: 'slot', depth: 2, slotId: 'read-incoming', suffix: ';' },
    { kind: 'composite', depth: 2, segments: [{ kind: 'fixed', value: 'if (' }, { kind: 'slot', slotId: 'incoming-debt-condition' }, { kind: 'fixed', value: ') {' }] },
    { kind: 'slot', depth: 2, slotId: 'reduce-missing', suffix: ';' },
    { kind: 'fixed', depth: 2, value: '}' },
    { kind: 'slot', depth: 2, slotId: 'debit-incoming', suffix: ';' },
    { kind: 'composite', depth: 2, segments: [{ kind: 'fixed', value: 'while (' }, { kind: 'slot', slotId: 'shrink-condition' }, { kind: 'fixed', value: ') {' }] },
    { kind: 'slot', depth: 2, slotId: 'measure-window', suffix: ';' },
    { kind: 'composite', depth: 2, segments: [{ kind: 'fixed', value: 'if (' }, { kind: 'slot', slotId: 'shorter-condition' }, { kind: 'fixed', value: ') {' }] },
    { kind: 'slot', depth: 2, slotId: 'save-best', suffix: ';' },
    { kind: 'fixed', depth: 2, value: '}' },
    { kind: 'slot', depth: 2, slotId: 'read-outgoing', suffix: ';' },
    { kind: 'slot', depth: 2, slotId: 'credit-outgoing', suffix: ';' },
    { kind: 'composite', depth: 2, segments: [{ kind: 'fixed', value: 'if (' }, { kind: 'slot', slotId: 'restored-condition' }, { kind: 'fixed', value: ') {' }] },
    { kind: 'slot', depth: 2, slotId: 'increase-missing', suffix: ';' },
    { kind: 'fixed', depth: 2, value: '}' },
    { kind: 'slot', depth: 2, slotId: 'advance-left', suffix: ';' },
    { kind: 'fixed', depth: 2, value: '}' },
    { kind: 'slot', depth: 2, slotId: 'advance-right', suffix: ';' },
    { kind: 'fixed', depth: 1, value: '}' },
    { kind: 'composite', depth: 1, segments: [{ kind: 'fixed', value: 'if (' }, { kind: 'slot', slotId: 'no-answer-condition' }, { kind: 'fixed', value: ') {' }] },
    { kind: 'composite', depth: 2, segments: [{ kind: 'fixed', value: 'return ' }, { kind: 'slot', slotId: 'empty-result' }, { kind: 'fixed', value: ';' }] },
    { kind: 'fixed', depth: 1, value: '}' },
    { kind: 'composite', depth: 1, segments: [{ kind: 'fixed', value: 'return ' }, { kind: 'slot', slotId: 'window-result' }, { kind: 'fixed', value: ';' }] },
  ],
}

export const MINIMUM_WINDOW_REFERENCE_STEPS: LogicCodeStep[] = [
  { id: 'initialize', order: 1, stepLabel: '初始化校准台', worldAction: '清空欠账表并把需求卡放到起点。', logicPurpose: '准备固定字符计数数组与目标索引。', role: 'action', depth: 0, tone: 'yellow', code: 'int[] need = new int[128];\nint targetIndex = 0;', semanticCheck: 'initialize', conceptIds: ['need-table', 'target-index'] },
  { id: 'target-loop-open', order: 2, stepLabel: '逐字登记目标', worldAction: '需求卡未到末尾就继续登记。', logicPurpose: '遍历目标字符串的每个字符及重复次数。', role: 'open-scope', depth: 0, tone: 'ink', code: 'while (targetIndex < t.length()) {', semanticCheck: 'targetLoop', conceptIds: ['target-text', 'target-index', 'target-registration', 'string-length'] },
  { id: 'read-target', order: 3, stepLabel: '读取目标字符', worldAction: '读取需求卡当前字符。', logicPurpose: '保存字符编码供计数数组索引。', role: 'action', depth: 1, tone: 'steel', code: 'int targetChar = t.charAt(targetIndex);', semanticCheck: 'readTarget', conceptIds: ['target-text', 'target-index', 'target-character', 'string-char-at'] },
  { id: 'add-target-debt', order: 4, stepLabel: '增加字符欠账', worldAction: '目标字符对应欠账增加一次。', logicPurpose: '重复目标字符必须累计多次。', role: 'action', depth: 1, tone: 'coral', code: 'need[targetChar]++;', semanticCheck: 'addTargetDebt', conceptIds: ['target-character', 'need-table', 'target-registration'] },
  { id: 'advance-target', order: 5, stepLabel: '需求卡前进', worldAction: '当前字符登记完成，需求卡前进。', logicPurpose: '保证目标登记循环终止。', role: 'action', depth: 1, tone: 'steel', code: 'targetIndex++;', semanticCheck: 'advanceTarget', conceptIds: ['target-index'] },
  { id: 'target-loop-close', order: 6, stepLabel: '完成目标登记', worldAction: '全部目标字符已经进入欠账表。', logicPurpose: '闭合目标登记循环。', role: 'close-scope', depth: 0, tone: 'ink', code: '}', semanticCheck: 'scopes', conceptIds: ['target-registration'] },
  { id: 'prepare-window', order: 7, stepLabel: '准备窗口状态', worldAction: '左右标尺归零，总欠账与历史封条就位。', logicPurpose: '初始化扩张、收缩和最短结果状态。', role: 'action', depth: 0, tone: 'yellow', code: 'int left = 0;\nint right = 0;\nint missing = t.length();\nint bestStart = 0;\nint bestLength = s.length() + 1;', semanticCheck: 'prepareWindow', conceptIds: ['left-boundary', 'right-boundary', 'missing-count', 'best-window', 'string-length'] },
  { id: 'source-loop-open', order: 8, stepLabel: '向右扫描文字带', worldAction: '右标尺未到末尾就开始新一轮扩张。', logicPurpose: '用外层 while 遍历源字符串。', role: 'open-scope', depth: 0, tone: 'ink', code: 'while (right < s.length()) {', semanticCheck: 'sourceLoop', conceptIds: ['source-text', 'right-boundary', 'source-scan', 'string-length'] },
  { id: 'read-incoming', order: 9, stepLabel: '读取入窗字符', worldAction: '读取右标尺当前字符。', logicPurpose: '共享给欠账判断和入窗记账。', role: 'action', depth: 1, tone: 'steel', code: 'int incoming = s.charAt(right);', semanticCheck: 'readIncoming', conceptIds: ['source-text', 'right-boundary', 'incoming-character', 'string-char-at'] },
  { id: 'incoming-check-open', order: 10, stepLabel: '检查字符是否欠缺', worldAction: '字符仍有正欠账时进入补齐分支。', logicPurpose: '必须在字符余额减一之前判断。', role: 'open-scope', depth: 1, tone: 'coral', code: 'if (need[incoming] > 0) {', semanticCheck: 'incomingCheck', conceptIds: ['incoming-character', 'need-table', 'incoming-needed'] },
  { id: 'reduce-missing', order: 11, stepLabel: '补齐一项总欠账', worldAction: '必要字符入窗，总欠账减一。', logicPurpose: '记录窗口距离完整覆盖还差多少字符。', role: 'action', depth: 2, tone: 'teal', code: 'missing--;', semanticCheck: 'reduceMissing', conceptIds: ['missing-count', 'incoming-needed'] },
  { id: 'incoming-check-close', order: 12, stepLabel: '完成欠账检查', worldAction: '补齐判断完成。', logicPurpose: '闭合入窗欠账分支。', role: 'close-scope', depth: 1, tone: 'coral', code: '}', semanticCheck: 'scopes', conceptIds: ['incoming-needed'] },
  { id: 'debit-incoming', order: 13, stepLabel: '登记字符入窗', worldAction: '入窗字符余额减一。', logicPurpose: '负数余额表示窗口中有额外字符。', role: 'action', depth: 1, tone: 'teal', code: 'need[incoming]--;', semanticCheck: 'debitIncoming', conceptIds: ['incoming-character', 'need-table', 'incoming-debit'] },
  { id: 'shrink-loop-open', order: 14, stepLabel: '覆盖后持续收缩', worldAction: '总欠账归零，左侧开始反复收缩。', logicPurpose: '只在完整覆盖时寻找更短窗口。', role: 'open-scope', depth: 1, tone: 'ink', code: 'while (missing == 0) {', semanticCheck: 'shrinkLoop', conceptIds: ['missing-count', 'window-covered'] },
  { id: 'measure-window', order: 15, stepLabel: '量出当前窗口', worldAction: '用两侧标尺计算连续窗口长度。', logicPurpose: '窗口长度等于右减左再加一。', role: 'action', depth: 2, tone: 'yellow', code: 'int currentLength = right - left + 1;', semanticCheck: 'measureWindow', conceptIds: ['left-boundary', 'right-boundary', 'window-length'] },
  { id: 'shorter-check-open', order: 16, stepLabel: '检查是否更短', worldAction: '当前窗口比历史封条更短时进入更新。', logicPurpose: '历史最短只允许严格缩短。', role: 'open-scope', depth: 2, tone: 'yellow', code: 'if (currentLength < bestLength) {', semanticCheck: 'shorterCheck', conceptIds: ['window-length', 'best-window', 'shorter-decision'] },
  { id: 'save-best', order: 17, stepLabel: '封存最短窗口', worldAction: '保存当前左标尺和窗口长度。', logicPurpose: '起点和长度必须在同一分支共同更新。', role: 'action', depth: 2, tone: 'yellow', code: 'bestStart = left;\nbestLength = currentLength;', semanticCheck: 'saveBest', conceptIds: ['left-boundary', 'window-length', 'best-window'] },
  { id: 'shorter-check-close', order: 18, stepLabel: '完成最短比较', worldAction: '历史封条更新完毕。', logicPurpose: '闭合更短窗口分支。', role: 'close-scope', depth: 2, tone: 'yellow', code: '}', semanticCheck: 'scopes', conceptIds: ['shorter-decision'] },
  { id: 'read-outgoing', order: 19, stepLabel: '读取出窗字符', worldAction: '读取左标尺准备移出的字符。', logicPurpose: '共享给出窗记账和欠账恢复判断。', role: 'action', depth: 2, tone: 'steel', code: 'int outgoing = s.charAt(left);', semanticCheck: 'readOutgoing', conceptIds: ['source-text', 'left-boundary', 'outgoing-character', 'string-char-at'] },
  { id: 'credit-outgoing', order: 20, stepLabel: '撤销字符入窗', worldAction: '出窗字符余额加一。', logicPurpose: '必须先加回余额，再判断是否失去覆盖。', role: 'action', depth: 2, tone: 'coral', code: 'need[outgoing]++;', semanticCheck: 'creditOutgoing', conceptIds: ['outgoing-character', 'need-table', 'outgoing-credit'] },
  { id: 'restore-check-open', order: 21, stepLabel: '检查是否恢复欠账', worldAction: '余额重新为正时，窗口失去必要字符。', logicPurpose: '判断本轮收缩是否应停止。', role: 'open-scope', depth: 2, tone: 'coral', code: 'if (need[outgoing] > 0) {', semanticCheck: 'restoreCheck', conceptIds: ['outgoing-character', 'need-table', 'restored-debt'] },
  { id: 'increase-missing', order: 22, stepLabel: '恢复一项总欠账', worldAction: '必要字符出窗，总欠账加一。', logicPurpose: '让内层循环在失去覆盖后停止。', role: 'action', depth: 2, tone: 'coral', code: 'missing++;', semanticCheck: 'increaseMissing', conceptIds: ['missing-count', 'restored-debt'] },
  { id: 'restore-check-close', order: 23, stepLabel: '完成恢复检查', worldAction: '出窗欠账判断完成。', logicPurpose: '闭合恢复欠账分支。', role: 'close-scope', depth: 2, tone: 'coral', code: '}', semanticCheck: 'scopes', conceptIds: ['restored-debt'] },
  { id: 'advance-left', order: 24, stepLabel: '左标尺右移', worldAction: '出窗记账完成后，左标尺前进。', logicPurpose: '保证收缩循环每轮移除一个字符。', role: 'action', depth: 2, tone: 'steel', code: 'left++;', semanticCheck: 'advanceLeft', conceptIds: ['left-boundary'] },
  { id: 'shrink-loop-close', order: 25, stepLabel: '结束本轮收缩', worldAction: '窗口失去覆盖后停止收缩。', logicPurpose: '闭合覆盖收缩循环。', role: 'close-scope', depth: 1, tone: 'ink', code: '}', semanticCheck: 'scopes', conceptIds: ['window-covered'] },
  { id: 'advance-right', order: 26, stepLabel: '右标尺右移', worldAction: '扩张与收缩结束，右标尺前进。', logicPurpose: '保证源串扫描循环终止。', role: 'action', depth: 1, tone: 'steel', code: 'right++;', semanticCheck: 'advanceRight', conceptIds: ['right-boundary'] },
  { id: 'source-loop-close', order: 27, stepLabel: '完成文字带扫描', worldAction: '右标尺到达末尾。', logicPurpose: '闭合源串扫描循环。', role: 'close-scope', depth: 0, tone: 'ink', code: '}', semanticCheck: 'scopes', conceptIds: ['source-scan'] },
  { id: 'empty-result', order: 28, stepLabel: '处理无覆盖窗口', worldAction: '历史封条仍为空时交付空片段。', logicPurpose: '用哨兵边界识别不存在答案。', role: 'branch', depth: 0, tone: 'coral', code: 'if (bestLength > s.length()) {\n  return s.substring(0, 0);\n}', semanticCheck: 'emptyResult', conceptIds: ['source-text', 'best-window', 'no-window-boundary', 'string-length', 'string-substring', 'method-result'] },
  { id: 'return-window', order: 29, stepLabel: '交付最短窗口', worldAction: '按历史封条裁切源文字带。', logicPurpose: '返回历史最短起点到起点加长度。', role: 'result', depth: 0, tone: 'yellow', code: 'return s.substring(bestStart, bestStart + bestLength);', semanticCheck: 'returnWindow', conceptIds: ['source-text', 'best-window', 'string-substring', 'method-result'] },
]

export const composeMinimumWindowReferenceBody = () =>
  MINIMUM_WINDOW_REFERENCE_STEPS.map((step) => step.code).join('\n')

export const MINIMUM_WINDOW_MAPPINGS: CodeMappingEntry[] = [
  { id: 'source', category: 'scene', label: '源文字带', worldMeaning: '被左右标尺连续扫描的只读字符串。', code: 'String s', conceptIds: ['source-text'] },
  { id: 'target', category: 'scene', label: '目标需求卡', worldMeaning: '窗口必须覆盖的全部字符和重复次数。', code: 'String t', conceptIds: ['target-text'] },
  { id: 'need', category: 'scene', label: '字符欠账台', worldMeaning: '正数表示还欠，零表示刚好，负数表示窗口内有余量。', code: 'int[] need = new int[128]', conceptIds: ['need-table'] },
  { id: 'missing', category: 'scene', label: '总欠账读数', worldMeaning: '窗口距离完整覆盖还缺少的字符总数。', code: 'int missing = t.length()', conceptIds: ['missing-count'] },
  { id: 'left', category: 'scene', label: '左标尺', worldMeaning: '当前连续窗口的起点。', code: 'int left = 0', conceptIds: ['left-boundary'] },
  { id: 'right', category: 'scene', label: '右标尺', worldMeaning: '本轮准备纳入窗口的字符位置。', code: 'int right = 0', conceptIds: ['right-boundary'] },
  { id: 'best', category: 'scene', label: '历史最短封条', worldMeaning: '保存迄今最短覆盖窗口的起点和长度。', code: 'int bestStart; int bestLength;', conceptIds: ['best-window'] },
  { id: 'incoming', category: 'skill', label: '入窗字符', worldMeaning: '右标尺当前读取并准备记账的字符。', code: 'int incoming = s.charAt(right)', conceptIds: ['incoming-character'] },
  { id: 'outgoing', category: 'skill', label: '出窗字符', worldMeaning: '左标尺当前读取并准备移出的字符。', code: 'int outgoing = s.charAt(left)', conceptIds: ['outgoing-character'] },
  { id: 'target-registration', category: 'skill', label: '登记目标欠账', worldMeaning: '逐字累计目标需要的重复次数。', code: 'need[targetChar]++;', conceptIds: ['target-registration'] },
  { id: 'need-debit', category: 'skill', label: '字符入窗记账', worldMeaning: '先补齐总欠账，再把字符余额减一。', code: 'if (need[incoming] > 0) missing--;\nneed[incoming]--;', conceptIds: ['incoming-needed', 'incoming-debit'] },
  { id: 'need-credit', category: 'skill', label: '字符出窗记账', worldMeaning: '先把字符余额加一，再判断是否恢复总欠账。', code: 'need[outgoing]++;\nif (need[outgoing] > 0) missing++;', conceptIds: ['outgoing-credit', 'restored-debt'] },
  { id: 'shrink', category: 'syntax', label: '覆盖后收缩循环', worldMeaning: '只有总欠账为零时，窗口才可以从左侧继续缩短。', code: 'while (missing == 0) { ... }', conceptIds: ['window-covered'] },
  { id: 'record-best', category: 'skill', label: '封存更短窗口', worldMeaning: '用当前左右边界计算长度，并同步保存起点和长度。', code: 'if (currentLength < bestLength) { ... }', conceptIds: ['window-length', 'shorter-decision', 'best-window'] },
  { id: 'length', category: 'api', label: '字符串长度', worldMeaning: '控制目标、源串边界，并建立无答案哨兵。', code: 's.length() / t.length()', conceptIds: ['string-length'] },
  { id: 'char-at', category: 'api', label: '读取指定字符', worldMeaning: '按目标索引或窗口边界读取字符编码。', code: 'text.charAt(index)', conceptIds: ['string-char-at'] },
  { id: 'substring', category: 'api', label: '截取连续子串', worldMeaning: '按起点（含）和终点（不含）裁切最终窗口。', code: 's.substring(start, end)', conceptIds: ['string-substring'] },
  { id: 'result', category: 'syntax', label: '返回字符串', worldMeaning: '有答案返回历史最短窗口，否则返回空片段。', code: 'return ...;', conceptIds: ['method-result', 'no-window-boundary'] },
]
