import type { AlgorithmConceptDefinition } from '../types'

export const RAIN_WATER_CONCEPTS: AlgorithmConceptDefinition[] = [
  {
    id: 'height-input',
    kind: 'input',
    label: '地形高度',
    worldMeaning: '峡谷中每个编号位置的柱高。',
    canonicalCode: 'height / height[index]',
    links: {
      sceneIds: ['terrain-columns'],
      skillIds: ['deploy', 'update-max', 'collect'],
      traceFields: ['terrain'],
      referenceStepIds: ['deploy', 'left-update-max', 'left-collect', 'right-update-max', 'right-collect'],
      mappingEntryIds: ['height'],
      structuredSlotIds: ['preparation', 'left-update-max', 'left-collect', 'right-update-max', 'right-collect'],
      semanticChecks: ['deploy', 'leftUpdateMax', 'leftCollect', 'rightUpdateMax', 'rightCollect'],
    },
  },
  {
    id: 'left-position',
    kind: 'state',
    label: '左侧巡线位置',
    worldMeaning: '黄色巡线员当前所在的地形编号。',
    canonicalCode: 'left',
    lifecycle: {
      initialization: '从 0 号位置出发。',
      reads: ['判断是否与右侧相遇', '读取当前柱高'],
      writes: ['左岸被选中后向内一步'],
      updateRule: 'left++',
    },
    links: {
      sceneIds: ['left-scout'],
      skillIds: ['deploy', 'advance'],
      traceFields: ['left'],
      referenceStepIds: ['deploy', 'patrol-open', 'left-advance', 'left-update-max', 'left-collect'],
      mappingEntryIds: ['left-position'],
      structuredSlotIds: ['preparation', 'loop-condition', 'left-advance', 'left-update-max', 'left-collect'],
      semanticChecks: ['deploy', 'patrol', 'leftAdvance', 'leftUpdateMax', 'leftCollect'],
    },
  },
  {
    id: 'right-position',
    kind: 'state',
    label: '右侧巡线位置',
    worldMeaning: '红色巡线员当前所在的地形编号。',
    canonicalCode: 'right',
    lifecycle: {
      initialization: '从最右侧位置出发。',
      reads: ['判断是否与左侧相遇', '读取当前柱高'],
      writes: ['右岸被选中后向内一步'],
      updateRule: 'right--',
    },
    links: {
      sceneIds: ['right-scout'],
      skillIds: ['deploy', 'advance'],
      traceFields: ['right'],
      referenceStepIds: ['deploy', 'patrol-open', 'right-advance', 'right-update-max', 'right-collect'],
      mappingEntryIds: ['right-position'],
      structuredSlotIds: ['preparation', 'loop-condition', 'right-advance', 'right-update-max', 'right-collect'],
      semanticChecks: ['deploy', 'patrol', 'rightAdvance', 'rightUpdateMax', 'rightCollect'],
    },
  },
  {
    id: 'left-maximum',
    kind: 'state',
    label: '左岸最高柱',
    worldMeaning: '黄色巡线员从左侧到当前位置见过的最高柱，同时保留来源编号。',
    canonicalCode: 'leftMax',
    lifecycle: {
      initialization: '读取 0 号柱高。',
      reads: ['与右岸最高柱比较', '计算左侧当前积水'],
      writes: ['左侧巡线员移入新位置后'],
      updateRule: 'leftMax = Math.max(leftMax, height[left])',
    },
    links: {
      sceneIds: ['left-maximum-readout', 'left-maximum-marker'],
      skillIds: ['deploy', 'compare', 'update-max', 'collect'],
      traceFields: ['leftMax', 'leftMaxIndex'],
      referenceStepIds: ['deploy', 'compare', 'left-update-max', 'left-collect'],
      mappingEntryIds: ['left-maximum'],
      structuredSlotIds: ['preparation', 'shore-condition', 'left-update-max', 'left-collect'],
      semanticChecks: ['deploy', 'compare', 'leftUpdateMax', 'leftCollect'],
    },
  },
  {
    id: 'right-maximum',
    kind: 'state',
    label: '右岸最高柱',
    worldMeaning: '红色巡线员从右侧到当前位置见过的最高柱，同时保留来源编号。',
    canonicalCode: 'rightMax',
    lifecycle: {
      initialization: '读取最右侧柱高。',
      reads: ['与左岸最高柱比较', '计算右侧当前积水'],
      writes: ['右侧巡线员移入新位置后'],
      updateRule: 'rightMax = Math.max(rightMax, height[right])',
    },
    links: {
      sceneIds: ['right-maximum-readout', 'right-maximum-marker'],
      skillIds: ['deploy', 'compare', 'update-max', 'collect'],
      traceFields: ['rightMax', 'rightMaxIndex'],
      referenceStepIds: ['deploy', 'compare', 'right-update-max', 'right-collect'],
      mappingEntryIds: ['right-maximum'],
      structuredSlotIds: ['preparation', 'shore-condition', 'right-update-max', 'right-collect'],
      semanticChecks: ['deploy', 'compare', 'rightUpdateMax', 'rightCollect'],
    },
  },
  {
    id: 'water-total',
    kind: 'state',
    label: '累计积水',
    worldMeaning: '已完成计算的所有位置水深之和。',
    canonicalCode: 'water',
    lifecycle: {
      initialization: '从 0 格开始。',
      reads: ['展示当前总量', '巡检结束后返回'],
      writes: ['每次计算出当前位置水深后'],
      updateRule: 'water += shoreMax - height[index]',
    },
    links: {
      sceneIds: ['water-total-readout', 'terrain-water'],
      skillIds: ['collect'],
      traceFields: ['water', 'totalWater'],
      referenceStepIds: ['deploy', 'left-collect', 'right-collect', 'return'],
      mappingEntryIds: ['water-total'],
      structuredSlotIds: ['preparation', 'left-collect', 'right-collect', 'result'],
      semanticChecks: ['deploy', 'leftCollect', 'rightCollect', 'return'],
    },
  },
  {
    id: 'patrol-boundary',
    kind: 'boundary',
    label: '巡检终止边界',
    worldMeaning: '两名巡线员未相遇时继续，相遇后停止。',
    canonicalCode: 'left < right',
    links: {
      sceneIds: ['left-scout', 'right-scout'],
      skillIds: ['patrol'],
      traceFields: ['left', 'right'],
      referenceStepIds: ['patrol-open', 'scopes-close'],
      mappingEntryIds: ['while'],
      structuredSlotIds: ['loop-condition'],
      semanticChecks: ['patrol', 'scopes'],
    },
  },
  {
    id: 'lower-shore-decision',
    kind: 'control',
    label: '选择较低最高岸线',
    worldMeaning: '每轮比较两侧已见最高柱，只处理较低的一侧。',
    canonicalCode: 'leftMax <= rightMax',
    links: {
      sceneIds: ['left-maximum-readout', 'right-maximum-readout'],
      skillIds: ['compare'],
      traceFields: ['selectedSide'],
      referenceStepIds: ['compare', 'alternate'],
      mappingEntryIds: ['if-else'],
      structuredSlotIds: ['shore-condition'],
      semanticChecks: ['compare', 'alternate'],
    },
  },
  {
    id: 'advance-selected-shore',
    kind: 'operation',
    label: '低岸向内移动',
    worldMeaning: '先进入新位置，再更新和计算该位置。',
    canonicalCode: 'left++ / right--',
    links: {
      sceneIds: ['left-scout', 'right-scout'],
      skillIds: ['advance'],
      traceFields: ['left', 'right'],
      referenceStepIds: ['left-advance', 'right-advance'],
      mappingEntryIds: ['advance'],
      structuredSlotIds: ['left-advance', 'right-advance'],
      semanticChecks: ['leftAdvance', 'rightAdvance'],
    },
  },
  {
    id: 'maximum-update',
    kind: 'operation',
    label: '更新本侧最高柱',
    worldMeaning: '比较旧记录和当前柱高，保留更高者及其位置。',
    canonicalCode: 'shoreMax = Math.max(shoreMax, height[index])',
    links: {
      sceneIds: ['left-maximum-marker', 'right-maximum-marker'],
      skillIds: ['update-max'],
      traceFields: ['leftMax', 'rightMax', 'leftMaxIndex', 'rightMaxIndex'],
      referenceStepIds: ['left-update-max', 'right-update-max'],
      mappingEntryIds: ['update-maximum'],
      structuredSlotIds: ['left-update-max', 'right-update-max'],
      semanticChecks: ['leftUpdateMax', 'rightUpdateMax'],
    },
  },
  {
    id: 'water-depth',
    kind: 'operation',
    label: '当前位置水深',
    worldMeaning: '本侧最高柱减去当前柱高，得到该位置可留下的水。',
    canonicalCode: 'shoreMax - height[index]',
    links: {
      sceneIds: ['terrain-water', 'runtime-message'],
      skillIds: ['collect'],
      traceFields: ['water', 'changedIndex'],
      referenceStepIds: ['left-collect', 'right-collect'],
      mappingEntryIds: ['collect'],
      structuredSlotIds: ['left-collect', 'right-collect'],
      semanticChecks: ['leftCollect', 'rightCollect'],
    },
  },
  {
    id: 'array-length',
    kind: 'api',
    label: '数组长度',
    worldMeaning: '用来找到最右侧巡线员的起点。',
    canonicalCode: 'height.length',
    links: {
      sceneIds: ['terrain-columns'],
      skillIds: ['deploy'],
      traceFields: ['terrain'],
      referenceStepIds: ['deploy'],
      mappingEntryIds: ['length'],
      structuredSlotIds: ['preparation'],
      semanticChecks: ['deploy'],
    },
  },
  {
    id: 'math-max',
    kind: 'api',
    label: '保留较高值',
    worldMeaning: '在旧最高柱和当前柱之间选择更高者。',
    canonicalCode: 'Math.max(oldMax, height[index])',
    links: {
      sceneIds: ['left-maximum-marker', 'right-maximum-marker'],
      skillIds: ['update-max'],
      traceFields: ['leftMax', 'rightMax'],
      referenceStepIds: ['left-update-max', 'right-update-max'],
      mappingEntryIds: ['math-max'],
      structuredSlotIds: ['left-update-max', 'right-update-max'],
      semanticChecks: ['leftUpdateMax', 'rightUpdateMax'],
    },
  },
  {
    id: 'method-result',
    kind: 'output',
    label: '返回总积水',
    worldMeaning: '巡检结束后交付累计的全部积水。',
    canonicalCode: 'return water',
    links: {
      sceneIds: ['water-total-readout'],
      skillIds: [],
      traceFields: ['totalWater'],
      referenceStepIds: ['return'],
      mappingEntryIds: ['result'],
      structuredSlotIds: ['result'],
      semanticChecks: ['return'],
    },
  },
]
