import type {
  CodeMappingEntry,
  LogicCodeStep,
  StructuredScaffold,
} from '../types'

export const RAIN_WATER_SCAFFOLD: StructuredScaffold = {
  methodOpen: 'int trap(int[] height) {',
  methodClose: '}',
  slots: [
    {
      id: 'preparation',
      label: '准备双端状态',
      responsibility: '定义左右位置、两侧岸线和积水总量。',
      lineCount: 5,
      conceptIds: ['height-input', 'left-position', 'right-position', 'left-maximum', 'right-maximum', 'water-total', 'array-length'],
    },
    {
      id: 'loop-condition',
      label: '巡检条件',
      responsibility: '两名巡线员未相遇时继续。',
      lineCount: 1,
      conceptIds: ['left-position', 'right-position', 'patrol-boundary'],
    },
    {
      id: 'shore-condition',
      label: '选择较低岸线',
      responsibility: '比较左右已知最高岸线。',
      lineCount: 1,
      conceptIds: ['left-maximum', 'right-maximum', 'lower-shore-decision'],
    },
    {
      id: 'left-advance',
      label: '左侧向内',
      responsibility: '左岸较低时，先让左侧位置前进一步。',
      lineCount: 1,
      conceptIds: ['left-position', 'advance-selected-shore'],
    },
    {
      id: 'left-update-max',
      label: '更新左岸最高柱',
      responsibility: '比较旧记录与当前柱高，保存更高者。',
      lineCount: 1,
      conceptIds: ['height-input', 'left-position', 'left-maximum', 'maximum-update', 'math-max'],
    },
    {
      id: 'left-collect',
      label: '计算左侧积水',
      responsibility: '用左岸最高柱减当前柱高并累加。',
      lineCount: 1,
      conceptIds: ['height-input', 'left-position', 'left-maximum', 'water-depth', 'water-total'],
    },
    {
      id: 'right-advance',
      label: '右侧向内',
      responsibility: '右岸较低时，先让右侧位置后退一步。',
      lineCount: 1,
      conceptIds: ['right-position', 'advance-selected-shore'],
    },
    {
      id: 'right-update-max',
      label: '更新右岸最高柱',
      responsibility: '比较旧记录与当前柱高，保存更高者。',
      lineCount: 1,
      conceptIds: ['height-input', 'right-position', 'right-maximum', 'maximum-update', 'math-max'],
    },
    {
      id: 'right-collect',
      label: '计算右侧积水',
      responsibility: '用右岸最高柱减当前柱高并累加。',
      lineCount: 1,
      conceptIds: ['height-input', 'right-position', 'right-maximum', 'water-depth', 'water-total'],
    },
    {
      id: 'result',
      label: '返回总量',
      responsibility: '返回整段巡检累加的雨水。',
      lineCount: 1,
      conceptIds: ['water-total', 'method-result'],
    },
  ],
  body: [
    { kind: 'slot', depth: 1, slotId: 'preparation', suffix: ';' },
    {
      kind: 'composite',
      depth: 1,
      segments: [
        { kind: 'fixed', value: 'while (' },
        { kind: 'slot', slotId: 'loop-condition' },
        { kind: 'fixed', value: ') {' },
      ],
    },
    {
      kind: 'composite',
      depth: 2,
      segments: [
        { kind: 'fixed', value: 'if (' },
        { kind: 'slot', slotId: 'shore-condition' },
        { kind: 'fixed', value: ') {' },
      ],
    },
    { kind: 'slot', depth: 2, slotId: 'left-advance', suffix: ';' },
    { kind: 'slot', depth: 2, slotId: 'left-update-max', suffix: ';' },
    { kind: 'slot', depth: 2, slotId: 'left-collect', suffix: ';' },
    { kind: 'fixed', depth: 2, value: '} else {' },
    { kind: 'slot', depth: 2, slotId: 'right-advance', suffix: ';' },
    { kind: 'slot', depth: 2, slotId: 'right-update-max', suffix: ';' },
    { kind: 'slot', depth: 2, slotId: 'right-collect', suffix: ';' },
    { kind: 'fixed', depth: 2, value: '}' },
    { kind: 'fixed', depth: 1, value: '}' },
    {
      kind: 'composite',
      depth: 1,
      segments: [
        { kind: 'fixed', value: 'return ' },
        { kind: 'slot', slotId: 'result' },
        { kind: 'fixed', value: ';' },
      ],
    },
  ],
}

export const RAIN_WATER_REFERENCE_STEPS: LogicCodeStep[] = [
  {
    id: 'deploy',
    order: 1,
    skillLabel: '双端就位',
    worldAction: '左右巡线员站在地形两端，读取起始岸线。',
    logicPurpose: '创建双指针、岸线状态和积水累加器。',
    role: 'action',
    depth: 0,
    tone: 'yellow',
    code: `int left = 0;
int right = height.length - 1;
int leftMax = height.length == 0 ? 0 : height[left];
int rightMax = height.length == 0 ? 0 : height[right];
int water = 0;`,
    semanticCheck: 'deploy',
    conceptIds: ['height-input', 'left-position', 'right-position', 'left-maximum', 'right-maximum', 'water-total', 'array-length'],
  },
  {
    id: 'patrol-open',
    order: 2,
    skillLabel: '巡检直到相遇',
    worldAction: '只要两名巡线员还未相遇，就开始新一轮。',
    logicPurpose: '用 while 重复同一套巡检规则。',
    role: 'open-scope',
    depth: 0,
    tone: 'ink',
    code: 'while (left < right) {',
    semanticCheck: 'patrol',
    conceptIds: ['left-position', 'right-position', 'patrol-boundary'],
  },
  {
    id: 'compare',
    order: 3,
    skillLabel: '选择较低岸线',
    worldAction: '比较两侧已见过的最高岸线。',
    logicPurpose: '较低一侧的岸线已足够决定本轮水深。',
    role: 'open-scope',
    depth: 1,
    tone: 'teal',
    code: 'if (leftMax <= rightMax) {',
    semanticCheck: 'compare',
    conceptIds: ['left-maximum', 'right-maximum', 'lower-shore-decision'],
  },
  {
    id: 'left-advance',
    order: 4,
    skillLabel: '低岸向内一步',
    worldAction: '左岸较低时，黄方先进入新位置。',
    logicPurpose: '保证结算的是新进入的地形，不重复结算旧位置。',
    role: 'action',
    depth: 2,
    tone: 'steel',
    code: 'left++;',
    semanticCheck: 'leftAdvance',
    conceptIds: ['left-position', 'advance-selected-shore'],
  },
  {
    id: 'left-update-max',
    order: 5,
    skillLabel: '更新最高柱',
    worldAction: '比较左岸旧记录和当前柱高，记住更高的一根。',
    logicPurpose: '让 leftMax 始终代表左侧迄今见过的最高柱。',
    role: 'action',
    depth: 2,
    tone: 'yellow',
    code: 'leftMax = Math.max(leftMax, height[left]);',
    semanticCheck: 'leftUpdateMax',
    conceptIds: ['height-input', 'left-position', 'left-maximum', 'maximum-update', 'math-max'],
  },
  {
    id: 'left-collect',
    order: 6,
    skillLabel: '计算当前积水',
    worldAction: '用左岸最高柱减去当前柱高。',
    logicPurpose: '得到左侧新位置的水深并累加到总量。',
    role: 'action',
    depth: 2,
    tone: 'coral',
    code: 'water += leftMax - height[left];',
    semanticCheck: 'leftCollect',
    conceptIds: ['height-input', 'left-position', 'left-maximum', 'water-depth', 'water-total'],
  },
  {
    id: 'alternate',
    order: 7,
    skillLabel: '切换到右岸',
    worldAction: '当左岸不再较低，改由红方执行本轮。',
    logicPurpose: '用 else 表达互斥的另一条执行路径。',
    role: 'branch',
    depth: 1,
    tone: 'teal',
    code: '} else {',
    semanticCheck: 'alternate',
    conceptIds: ['lower-shore-decision'],
  },
  {
    id: 'right-advance',
    order: 8,
    skillLabel: '低岸向内一步',
    worldAction: '右岸较低时，红方先进入新位置。',
    logicPurpose: '从右侧向中间收缩右指针。',
    role: 'action',
    depth: 2,
    tone: 'steel',
    code: 'right--;',
    semanticCheck: 'rightAdvance',
    conceptIds: ['right-position', 'advance-selected-shore'],
  },
  {
    id: 'right-update-max',
    order: 9,
    skillLabel: '更新最高柱',
    worldAction: '比较右岸旧记录和当前柱高，记住更高的一根。',
    logicPurpose: '让 rightMax 始终代表右侧迄今见过的最高柱。',
    role: 'action',
    depth: 2,
    tone: 'yellow',
    code: 'rightMax = Math.max(rightMax, height[right]);',
    semanticCheck: 'rightUpdateMax',
    conceptIds: ['height-input', 'right-position', 'right-maximum', 'maximum-update', 'math-max'],
  },
  {
    id: 'right-collect',
    order: 10,
    skillLabel: '计算当前积水',
    worldAction: '用右岸最高柱减去当前柱高。',
    logicPurpose: '得到右侧新位置的水深并累加到总量。',
    role: 'action',
    depth: 2,
    tone: 'coral',
    code: 'water += rightMax - height[right];',
    semanticCheck: 'rightCollect',
    conceptIds: ['height-input', 'right-position', 'right-maximum', 'water-depth', 'water-total'],
  },
  {
    id: 'scopes-close',
    order: 11,
    skillLabel: '结束本轮',
    worldAction: '收住分支，再回到巡检条件。',
    logicPurpose: '明确 if/else 和 while 的作用域边界。',
    role: 'close-scope',
    depth: 1,
    tone: 'ink',
    code: `  }
}`,
    semanticCheck: 'scopes',
    conceptIds: ['patrol-boundary', 'lower-shore-decision'],
  },
  {
    id: 'return',
    order: 12,
    skillLabel: '交付巡检结果',
    worldAction: '巡检完成后交付累计的雨水总量。',
    logicPurpose: '将算法结果作为 int 返回。',
    role: 'result',
    depth: 0,
    tone: 'yellow',
    code: 'return water;',
    semanticCheck: 'return',
    conceptIds: ['water-total', 'method-result'],
  },
]

export const composeRainWaterReferenceBody = () =>
  RAIN_WATER_REFERENCE_STEPS.map((step) => step.code).join('\n')

export const RAIN_WATER_MAPPINGS: CodeMappingEntry[] = [
  { id: 'height', category: 'scene', label: '地形高度', worldMeaning: '每个编号位置的柱高，是所有比较和减法的原始输入。', code: 'height[index]', conceptIds: ['height-input'] },
  { id: 'left-position', category: 'scene', label: '左侧巡线位置', worldMeaning: '黄色巡线员当前所在的编号。', code: 'left', conceptIds: ['left-position'] },
  { id: 'right-position', category: 'scene', label: '右侧巡线位置', worldMeaning: '红色巡线员当前所在的编号。', code: 'right', conceptIds: ['right-position'] },
  { id: 'left-maximum', category: 'scene', label: '左岸最高柱', worldMeaning: '左侧迄今见过的最高柱高；场景同时标出来源编号。', code: 'leftMax', conceptIds: ['left-maximum'] },
  { id: 'right-maximum', category: 'scene', label: '右岸最高柱', worldMeaning: '右侧迄今见过的最高柱高；场景同时标出来源编号。', code: 'rightMax', conceptIds: ['right-maximum'] },
  { id: 'water-total', category: 'scene', label: '累计积水', worldMeaning: '每个已处理位置水深的累加结果。', code: 'water', conceptIds: ['water-total'] },
  { id: 'while', category: 'syntax', label: '反复巡检', worldMeaning: '在左右位置相遇前重复整条因果链。', code: 'while (left < right)', conceptIds: ['patrol-boundary'] },
  { id: 'if-else', category: 'syntax', label: '选择较低最高岸线', worldMeaning: '每轮只处理已知最高柱较低的一侧。', code: 'if (...) { ... } else { ... }', conceptIds: ['lower-shore-decision'] },
  { id: 'advance', category: 'skill', label: '低岸向内一步', worldMeaning: '先进入新位置，再更新状态和计算水深。', code: 'left++ / right--', conceptIds: ['advance-selected-shore'] },
  { id: 'update-maximum', category: 'skill', label: '更新最高柱', worldMeaning: '比较旧记录与当前柱高，保存更高者。', code: 'shoreMax = Math.max(shoreMax, height[index])', conceptIds: ['maximum-update'] },
  { id: 'collect', category: 'skill', label: '计算当前积水', worldMeaning: '用更新后的本侧最高柱减当前柱高，再累加到总量。', code: 'water += shoreMax - height[index]', conceptIds: ['water-depth', 'water-total'] },
  { id: 'length', category: 'api', label: '数组长度', worldMeaning: '定位最右侧巡线员的起点。', code: 'height.length', conceptIds: ['array-length'] },
  { id: 'math-max', category: 'api', label: '保留较高值', worldMeaning: '在旧最高柱和当前柱之间选择更高者。', code: 'Math.max(currentMax, height[index])', conceptIds: ['math-max'] },
  { id: 'result', category: 'syntax', label: '返回总积水', worldMeaning: '巡检结束后交付同一个累加器。', code: 'return water', conceptIds: ['method-result', 'water-total'] },
]
