import type { AlgorithmConceptDefinition } from '../types'

export const ANAGRAM_CONCEPTS: AlgorithmConceptDefinition[] = [
  {
    id: 'source-string',
    kind: 'input',
    label: '源信号带',
    worldMeaning: '等待扫描的完整小写字母字符串。',
    canonicalCode: 's',
    links: {
      sceneIds: ['source-track'],
      skillIds: ['scan-source', 'add-incoming', 'if-overflow'],
      traceFields: ['source'],
      referenceStepIds: ['scan-source-open', 'add-incoming', 'remove-outgoing'],
      mappingEntryIds: ['source-string'],
      structuredSlotIds: ['source-loop-condition', 'add-incoming', 'remove-outgoing'],
      semanticChecks: ['sourceLoop', 'addIncoming', 'removeOutgoing'],
    },
  },
  {
    id: 'pattern-string',
    kind: 'input',
    label: '目标信号卡',
    worldMeaning: '决定目标频谱和固定窗口宽度的字符串。',
    canonicalCode: 'p',
    links: {
      sceneIds: ['pattern-card'],
      skillIds: ['prepare', 'if-overflow'],
      traceFields: ['pattern'],
      referenceStepIds: ['scan-pattern-open', 'count-pattern', 'if-overflow-open'],
      mappingEntryIds: ['pattern-string'],
      structuredSlotIds: ['pattern-loop-condition', 'target-count', 'overflow-condition'],
      semanticChecks: ['patternLoop', 'targetCount', 'overflowCondition'],
    },
  },
  {
    id: 'target-counts',
    kind: 'state',
    label: '目标频谱',
    worldMeaning: '记录目标串中 a-z 每个字母需要出现多少次。',
    canonicalCode: 'target[26]',
    lifecycle: {
      initialization: '创建 26 个全为 0 的频谱格。',
      reads: ['与当前窗口频谱逐格比较'],
      writes: ['目标读头经过一个字母时'],
      updateRule: "target[p.charAt(i) - 'a']++",
    },
    links: {
      sceneIds: ['target-spectrum'],
      skillIds: ['prepare', 'if-match'],
      traceFields: ['targetCounts'],
      referenceStepIds: ['prepare', 'count-pattern', 'if-match-open'],
      mappingEntryIds: ['target-spectrum', 'new-count-array', 'arrays-equals'],
      structuredSlotIds: ['preparation', 'target-count', 'match-condition'],
      semanticChecks: ['initialize', 'targetCount', 'matchCondition'],
    },
  },
  {
    id: 'window-counts',
    kind: 'state',
    label: '窗口频谱',
    worldMeaning: '记录当前左右夹具之间 a-z 每个字母的出现次数。',
    canonicalCode: 'window[26]',
    lifecycle: {
      initialization: '创建 26 个全为 0 的频谱格。',
      reads: ['与目标频谱逐格比较'],
      writes: ['右侧字母进入时加一', '左侧字母离开时减一'],
      updateRule: '进入 +1，离开 -1',
    },
    links: {
      sceneIds: ['window-spectrum'],
      skillIds: ['prepare', 'add-incoming', 'if-overflow', 'if-match'],
      traceFields: ['windowCounts'],
      referenceStepIds: ['prepare', 'add-incoming', 'remove-outgoing', 'if-match-open'],
      mappingEntryIds: ['window-spectrum', 'new-count-array', 'arrays-equals'],
      structuredSlotIds: ['preparation', 'add-incoming', 'remove-outgoing', 'match-condition'],
      semanticChecks: ['initialize', 'addIncoming', 'removeOutgoing', 'matchCondition'],
    },
  },
  {
    id: 'left-index',
    kind: 'state',
    label: '窗口左边界',
    worldMeaning: '左侧夹具所在位置，也是匹配窗口的起点。',
    canonicalCode: 'left',
    lifecycle: {
      initialization: '从 0 号位置开始。',
      reads: ['读取离开字符', '计算窗口宽度', '记录匹配起点'],
      writes: ['旧字符从频谱扣除之后'],
      updateRule: 'left++',
    },
    links: {
      sceneIds: ['left-clamp', 'window-span'],
      skillIds: ['prepare', 'if-overflow', 'if-match'],
      traceFields: ['left', 'leavingIndex', 'matches'],
      referenceStepIds: ['prepare', 'remove-outgoing', 'advance-left', 'record-index'],
      mappingEntryIds: ['left-index', 'window-width', 'record-index'],
      structuredSlotIds: ['preparation', 'overflow-condition', 'remove-outgoing', 'advance-left', 'record-index'],
      semanticChecks: ['initialize', 'overflowCondition', 'removeOutgoing', 'leftAdvance', 'recordIndex'],
    },
  },
  {
    id: 'pattern-index',
    kind: 'state',
    label: '目标读头',
    worldMeaning: '依次读取目标卡每个字母的位置。',
    canonicalCode: 'i',
    lifecycle: {
      initialization: '从 0 号位置开始。',
      reads: ['读取目标字母'],
      writes: ['每轮目标扫描结束'],
      updateRule: 'i++',
    },
    links: {
      sceneIds: ['pattern-reader'],
      skillIds: ['prepare'],
      traceFields: ['patternIndex'],
      referenceStepIds: ['scan-pattern-open', 'count-pattern'],
      mappingEntryIds: ['pattern-index', 'for-loop'],
      structuredSlotIds: ['pattern-loop-init', 'pattern-loop-condition', 'pattern-loop-update', 'target-count'],
      semanticChecks: ['patternLoop', 'targetCount'],
    },
  },
  {
    id: 'right-index',
    kind: 'state',
    label: '窗口右探针',
    worldMeaning: '逐字读取源信号并扩展窗口右侧的位置。',
    canonicalCode: 'right',
    lifecycle: {
      initialization: '从 0 号位置开始。',
      reads: ['读取进入字符', '计算窗口宽度'],
      writes: ['每轮源串扫描结束'],
      updateRule: 'right++',
    },
    links: {
      sceneIds: ['right-probe', 'window-span'],
      skillIds: ['scan-source', 'add-incoming', 'if-overflow', 'if-match'],
      traceFields: ['right', 'enteringIndex'],
      referenceStepIds: ['scan-source-open', 'add-incoming', 'if-overflow-open', 'if-match-open'],
      mappingEntryIds: ['right-index', 'for-loop', 'window-width'],
      structuredSlotIds: ['source-loop-init', 'source-loop-condition', 'source-loop-update', 'add-incoming', 'overflow-condition'],
      semanticChecks: ['sourceLoop', 'addIncoming', 'overflowCondition'],
    },
  },
  {
    id: 'result-indices',
    kind: 'output',
    label: '命中索引纸带',
    worldMeaning: '按扫描顺序保存全部异位词窗口起点。',
    canonicalCode: 'result',
    lifecycle: {
      initialization: '创建空的整数列表。',
      reads: ['扫描结束后返回'],
      writes: ['频谱匹配时追加 left'],
      updateRule: 'result.add(left)',
    },
    links: {
      sceneIds: ['match-tape'],
      skillIds: ['prepare', 'if-match'],
      traceFields: ['matches'],
      referenceStepIds: ['prepare', 'record-index', 'return-result'],
      mappingEntryIds: ['result-list', 'list-add', 'return-result'],
      structuredSlotIds: ['preparation', 'record-index', 'result'],
      semanticChecks: ['initialize', 'recordIndex', 'returnResult'],
    },
  },
  {
    id: 'alphabet-offset',
    kind: 'operation',
    label: '字母频谱编号',
    worldMeaning: '把 a-z 字母换算成 0-25 号频谱格。',
    canonicalCode: "charAt(index) - 'a'",
    links: {
      sceneIds: ['active-spectrum-cell'],
      skillIds: ['prepare', 'add-incoming', 'if-overflow'],
      traceFields: ['activeChar'],
      referenceStepIds: ['count-pattern', 'add-incoming', 'remove-outgoing'],
      mappingEntryIds: ['alphabet-offset', 'string-char-at'],
      structuredSlotIds: ['target-count', 'add-incoming', 'remove-outgoing'],
      semanticChecks: ['targetCount', 'addIncoming', 'removeOutgoing'],
    },
  },
  {
    id: 'window-width',
    kind: 'state',
    label: '当前窗口宽度',
    worldMeaning: '左右夹具之间包含两端字符的实时格数。',
    canonicalCode: 'right - left + 1',
    lifecycle: {
      initialization: '右探针尚未进入时为 0。',
      reads: ['判断是否超过目标长度', '确认窗口已达到固定宽度'],
      writes: ['右探针或左夹具移动后重新计算'],
      updateRule: 'right - left + 1',
    },
    links: {
      sceneIds: ['window-span', 'width-readout'],
      skillIds: ['if-overflow', 'if-match'],
      traceFields: ['left', 'right'],
      referenceStepIds: ['if-overflow-open', 'if-match-open'],
      mappingEntryIds: ['window-width'],
      structuredSlotIds: ['overflow-condition', 'match-condition'],
      semanticChecks: ['overflowCondition', 'matchCondition'],
    },
  },
  {
    id: 'incoming-count',
    kind: 'operation',
    label: '纳入右侧字母',
    worldMeaning: '右探针读到的字母进入窗口，对应频谱格加一。',
    canonicalCode: "window[s.charAt(right) - 'a']++",
    links: {
      sceneIds: ['right-probe', 'window-spectrum'],
      skillIds: ['add-incoming'],
      traceFields: ['enteringIndex', 'windowCounts'],
      referenceStepIds: ['add-incoming'],
      mappingEntryIds: ['add-incoming'],
      structuredSlotIds: ['add-incoming'],
      semanticChecks: ['addIncoming'],
    },
  },
  {
    id: 'overflow-decision',
    kind: 'control',
    label: '窗口超宽判断',
    worldMeaning: '纳入右侧字母后，判断窗口是否超过目标宽度。',
    canonicalCode: 'right - left + 1 > p.length()',
    links: {
      sceneIds: ['overflow-indicator', 'width-readout'],
      skillIds: ['if-overflow'],
      traceFields: ['overflow'],
      referenceStepIds: ['if-overflow-open', 'if-overflow-close'],
      mappingEntryIds: ['overflow-condition', 'if-scope'],
      structuredSlotIds: ['overflow-condition'],
      semanticChecks: ['overflowCondition', 'scopes'],
    },
  },
  {
    id: 'outgoing-count',
    kind: 'operation',
    label: '移出左侧字母',
    worldMeaning: '先把即将离开的左侧字母从窗口频谱扣除。',
    canonicalCode: "window[s.charAt(left) - 'a']--",
    links: {
      sceneIds: ['left-clamp', 'window-spectrum'],
      skillIds: ['if-overflow'],
      traceFields: ['leavingIndex', 'windowCounts'],
      referenceStepIds: ['remove-outgoing'],
      mappingEntryIds: ['remove-outgoing'],
      structuredSlotIds: ['remove-outgoing'],
      semanticChecks: ['removeOutgoing'],
    },
  },
  {
    id: 'left-advance',
    kind: 'operation',
    label: '推进左边界',
    worldMeaning: '旧字母离开后，左夹具向右移动一格。',
    canonicalCode: 'left++',
    links: {
      sceneIds: ['left-clamp'],
      skillIds: ['if-overflow'],
      traceFields: ['left'],
      referenceStepIds: ['advance-left'],
      mappingEntryIds: ['advance-left'],
      structuredSlotIds: ['advance-left'],
      semanticChecks: ['leftAdvance'],
    },
  },
  {
    id: 'frequency-equality',
    kind: 'control',
    label: '频谱一致判断',
    worldMeaning: '固定宽度窗口的 26 个频次格与目标逐格相等。',
    canonicalCode: 'Arrays.equals(target, window)',
    links: {
      sceneIds: ['target-spectrum', 'window-spectrum', 'match-indicator'],
      skillIds: ['if-match'],
      traceFields: ['frequenciesMatch'],
      referenceStepIds: ['if-match-open', 'if-match-close'],
      mappingEntryIds: ['arrays-equals', 'match-condition'],
      structuredSlotIds: ['match-condition'],
      semanticChecks: ['matchCondition', 'scopes'],
    },
  },
  {
    id: 'record-index',
    kind: 'operation',
    label: '记录窗口起点',
    worldMeaning: '频谱一致时，把左夹具位置追加到命中纸带。',
    canonicalCode: 'result.add(left)',
    links: {
      sceneIds: ['match-tape'],
      skillIds: ['if-match'],
      traceFields: ['matches'],
      referenceStepIds: ['record-index'],
      mappingEntryIds: ['record-index', 'list-add'],
      structuredSlotIds: ['record-index'],
      semanticChecks: ['recordIndex'],
    },
  },
  {
    id: 'pattern-boundary',
    kind: 'boundary',
    label: '目标扫描边界',
    worldMeaning: '目标读头只扫描到 p 的末尾。',
    canonicalCode: 'i < p.length()',
    links: {
      sceneIds: ['pattern-reader', 'pattern-card'],
      skillIds: ['prepare'],
      traceFields: ['patternIndex'],
      referenceStepIds: ['scan-pattern-open', 'scan-pattern-close'],
      mappingEntryIds: ['for-loop', 'string-length'],
      structuredSlotIds: ['pattern-loop-condition'],
      semanticChecks: ['patternLoop'],
    },
  },
  {
    id: 'source-boundary',
    kind: 'boundary',
    label: '源串扫描边界',
    worldMeaning: '右探针只扫描到 s 的末尾。',
    canonicalCode: 'right < s.length()',
    links: {
      sceneIds: ['right-probe', 'source-track'],
      skillIds: ['scan-source'],
      traceFields: ['right'],
      referenceStepIds: ['scan-source-open', 'if-match-close'],
      mappingEntryIds: ['for-loop', 'string-length'],
      structuredSlotIds: ['source-loop-condition'],
      semanticChecks: ['sourceLoop'],
    },
  },
  {
    id: 'string-length',
    kind: 'api',
    label: '读取字符串长度',
    worldMeaning: '决定两个扫描循环的终点和固定窗口宽度。',
    canonicalCode: 's.length() / p.length()',
    links: {
      sceneIds: ['source-track', 'pattern-card', 'width-readout'],
      skillIds: ['prepare', 'scan-source', 'if-overflow'],
      traceFields: ['source', 'pattern'],
      referenceStepIds: ['scan-pattern-open', 'scan-source-open', 'if-overflow-open'],
      mappingEntryIds: ['string-length'],
      structuredSlotIds: ['pattern-loop-condition', 'source-loop-condition', 'overflow-condition'],
      semanticChecks: ['patternLoop', 'sourceLoop', 'overflowCondition'],
    },
  },
  {
    id: 'string-char-at',
    kind: 'api',
    label: '按位置读取字符',
    worldMeaning: '读取目标、进入窗口或离开窗口的指定字母。',
    canonicalCode: 'text.charAt(index)',
    links: {
      sceneIds: ['pattern-reader', 'right-probe', 'left-clamp'],
      skillIds: ['prepare', 'add-incoming', 'if-overflow'],
      traceFields: ['activeChar'],
      referenceStepIds: ['count-pattern', 'add-incoming', 'remove-outgoing'],
      mappingEntryIds: ['string-char-at'],
      structuredSlotIds: ['target-count', 'add-incoming', 'remove-outgoing'],
      semanticChecks: ['targetCount', 'addIncoming', 'removeOutgoing'],
    },
  },
  {
    id: 'arrays-equals',
    kind: 'api',
    label: '比较完整频谱',
    worldMeaning: '一次检查两份 26 格频谱是否逐格相同。',
    canonicalCode: 'Arrays.equals(target, window)',
    links: {
      sceneIds: ['target-spectrum', 'window-spectrum'],
      skillIds: ['if-match'],
      traceFields: ['frequenciesMatch'],
      referenceStepIds: ['if-match-open'],
      mappingEntryIds: ['arrays-equals'],
      structuredSlotIds: ['match-condition'],
      semanticChecks: ['matchCondition'],
    },
  },
  {
    id: 'list-add',
    kind: 'api',
    label: '追加结果索引',
    worldMeaning: '把新的匹配起点追加到结果列表末尾。',
    canonicalCode: 'result.add(left)',
    links: {
      sceneIds: ['match-tape'],
      skillIds: ['if-match'],
      traceFields: ['matches'],
      referenceStepIds: ['record-index'],
      mappingEntryIds: ['list-add'],
      structuredSlotIds: ['record-index'],
      semanticChecks: ['recordIndex'],
    },
  },
]
