import type { AlgorithmConceptDefinition } from '../types'

export const LONGEST_SUBSTRING_CONCEPTS: AlgorithmConceptDefinition[] = [
  {
    id: 'string-input',
    kind: 'input',
    label: '字符轨道',
    worldMeaning: '灯廊中按顺序排列、不可修改的全部字符。',
    canonicalCode: 's / s.charAt(index)',
    links: {
      sceneIds: ['character-track'],
      skillIds: ['scan', 'shrink-duplicates'],
      traceFields: ['source'],
      referenceStepIds: ['read-current', 'release-left'],
      mappingEntryIds: ['string-input'],
      structuredSlotIds: ['read-current', 'release-left'],
      semanticChecks: ['readCurrent', 'release'],
    },
  },
  {
    id: 'left-boundary',
    kind: 'state',
    label: '守窗员 / 左边界',
    worldMeaning: '守窗员驻守当前无重复窗口的最左侧，清退字符后带着左边界向右移动。',
    canonicalCode: 'left',
    lifecycle: {
      initialization: '从 0 号位置开始。',
      reads: ['读取待移出的左端字符', '计算当前窗口宽度'],
      writes: ['左端字符移出频次台后'],
      updateRule: 'left++',
    },
    links: {
      sceneIds: ['left-gate'],
      skillIds: ['initialize', 'shrink-duplicates', 'update-best'],
      traceFields: ['left'],
      referenceStepIds: ['initialize', 'release-left', 'advance-left', 'update-best'],
      mappingEntryIds: ['left-boundary'],
      structuredSlotIds: ['preparation', 'release-left', 'advance-left', 'update-best'],
      semanticChecks: ['initialize', 'release', 'moveLeft', 'updateBest'],
    },
  },
  {
    id: 'right-boundary',
    kind: 'state',
    label: '巡灯员 / 右边界',
    worldMeaning: '巡灯员用探照灯读取当前字符，并在每轮完成后带着右边界向前移动。',
    canonicalCode: 'right',
    lifecycle: {
      initialization: '从 0 号位置开始。',
      reads: ['检查是否到达末尾', '读取当前字符', '计算当前窗口宽度'],
      writes: ['完成本轮最长记录更新后'],
      updateRule: 'right++',
    },
    links: {
      sceneIds: ['right-scanner'],
      skillIds: ['initialize', 'scan', 'update-best'],
      traceFields: ['right'],
      referenceStepIds: ['initialize', 'scan-open', 'read-current', 'update-best', 'advance-right'],
      mappingEntryIds: ['right-boundary'],
      structuredSlotIds: ['preparation', 'scan-condition', 'read-current', 'update-best', 'advance-right'],
      semanticChecks: ['initialize', 'scan', 'readCurrent', 'updateBest', 'moveRight'],
    },
  },
  {
    id: 'frequency-table',
    kind: 'state',
    label: '字符频次台',
    worldMeaning: '记录每个 ASCII 字符当前是否位于灯廊窗口中。',
    canonicalCode: 'int[] counts = new int[128]',
    lifecycle: {
      initialization: '128 项全部为 0。',
      reads: ['判断当前字符是否重复'],
      writes: ['移出左端时减一', '纳入当前字符时加一'],
      updateRule: 'counts[outgoing]-- / counts[current]++',
    },
    links: {
      sceneIds: ['frequency-console'],
      skillIds: ['initialize', 'shrink-duplicates', 'admit-current'],
      traceFields: ['frequencies'],
      referenceStepIds: ['initialize', 'duplicate-open', 'release-left', 'admit-current'],
      mappingEntryIds: ['frequency-table', 'new-frequency-array', 'array-access'],
      structuredSlotIds: ['preparation', 'duplicate-condition', 'release-left', 'admit-current'],
      semanticChecks: ['initialize', 'duplicate', 'release', 'admit'],
    },
  },
  {
    id: 'current-character',
    kind: 'state',
    label: '当前字符',
    worldMeaning: '巡灯员本轮用探照灯读取、准备进入窗口的字符编码。',
    canonicalCode: 'current',
    lifecycle: {
      initialization: '每轮从巡灯员所在位置读取。',
      reads: ['判断是否重复', '纳入频次台'],
      writes: ['每轮扫描开始后'],
      updateRule: 'current = s.charAt(right)',
    },
    links: {
      sceneIds: ['current-character-readout'],
      skillIds: ['scan', 'shrink-duplicates', 'admit-current'],
      traceFields: ['currentCode'],
      referenceStepIds: ['read-current', 'duplicate-open', 'admit-current'],
      mappingEntryIds: ['current-character'],
      structuredSlotIds: ['read-current', 'duplicate-condition', 'admit-current'],
      semanticChecks: ['readCurrent', 'duplicate', 'admit'],
    },
  },
  {
    id: 'best-length',
    kind: 'state',
    label: '最长记录',
    worldMeaning: '到当前扫描位置为止见过的最长无重复窗口及其长度。',
    canonicalCode: 'best',
    lifecycle: {
      initialization: '从 0 开始。',
      reads: ['与当前窗口宽度比较', '扫描结束后返回'],
      writes: ['当前字符安全纳入窗口后'],
      updateRule: 'best = Math.max(best, right - left + 1)',
    },
    links: {
      sceneIds: ['best-readout', 'best-window-marker'],
      skillIds: ['initialize', 'update-best'],
      traceFields: ['bestLength', 'bestStart', 'bestEnd'],
      referenceStepIds: ['initialize', 'update-best', 'return'],
      mappingEntryIds: ['best-length'],
      structuredSlotIds: ['preparation', 'update-best', 'result'],
      semanticChecks: ['initialize', 'updateBest', 'return'],
    },
  },
  {
    id: 'scan-boundary',
    kind: 'boundary',
    label: '扫描终止边界',
    worldMeaning: '巡灯员还在字符轨道范围内时继续巡查。',
    canonicalCode: 'right < s.length()',
    links: {
      sceneIds: ['right-scanner', 'character-track'],
      skillIds: ['scan'],
      traceFields: ['right', 'source'],
      referenceStepIds: ['scan-open', 'scan-close'],
      mappingEntryIds: ['outer-while'],
      structuredSlotIds: ['scan-condition'],
      semanticChecks: ['scan', 'scopes'],
    },
  },
  {
    id: 'duplicate-decision',
    kind: 'control',
    label: '重复字符判断',
    worldMeaning: '当前字符频次大于 0 时，窗口仍需从左侧收缩。',
    canonicalCode: 'counts[current] > 0',
    links: {
      sceneIds: ['duplicate-alarm', 'frequency-console'],
      skillIds: ['shrink-duplicates'],
      traceFields: ['currentCode', 'frequencies'],
      referenceStepIds: ['duplicate-open', 'duplicate-close'],
      mappingEntryIds: ['duplicate-while'],
      structuredSlotIds: ['duplicate-condition'],
      semanticChecks: ['duplicate', 'scopes'],
    },
  },
  {
    id: 'release-left-character',
    kind: 'operation',
    label: '移出左端字符',
    worldMeaning: '守窗员先从频次台撤销左边界指向的字符。',
    canonicalCode: 'counts[s.charAt(left)]--',
    links: {
      sceneIds: ['left-gate', 'frequency-console'],
      skillIds: ['shrink-duplicates'],
      traceFields: ['changedIndex', 'changedCode', 'frequencies'],
      referenceStepIds: ['release-left'],
      mappingEntryIds: ['release-left'],
      structuredSlotIds: ['release-left'],
      semanticChecks: ['release'],
    },
  },
  {
    id: 'move-left-boundary',
    kind: 'operation',
    label: '守窗员收紧左边界',
    worldMeaning: '字符退出窗口后，守窗员向右越过它并收紧左边界。',
    canonicalCode: 'left++',
    links: {
      sceneIds: ['left-gate'],
      skillIds: ['shrink-duplicates'],
      traceFields: ['left'],
      referenceStepIds: ['advance-left'],
      mappingEntryIds: ['advance-left'],
      structuredSlotIds: ['advance-left'],
      semanticChecks: ['moveLeft'],
    },
  },
  {
    id: 'admit-current-character',
    kind: 'operation',
    label: '纳入当前字符',
    worldMeaning: '重复清除后，把巡灯员读取的字符登记到窗口频次台。',
    canonicalCode: 'counts[current]++',
    links: {
      sceneIds: ['right-scanner', 'frequency-console'],
      skillIds: ['admit-current'],
      traceFields: ['windowEnd', 'frequencies'],
      referenceStepIds: ['admit-current'],
      mappingEntryIds: ['admit-current'],
      structuredSlotIds: ['admit-current'],
      semanticChecks: ['admit'],
    },
  },
  {
    id: 'window-width',
    kind: 'operation',
    label: '当前窗口宽度',
    worldMeaning: '守窗员与巡灯员所在位置都包含在窗口内，因此编号差还要加一。',
    canonicalCode: 'right - left + 1',
    links: {
      sceneIds: ['window-ruler'],
      skillIds: ['update-best'],
      traceFields: ['left', 'right', 'bestLength'],
      referenceStepIds: ['update-best'],
      mappingEntryIds: ['window-width'],
      structuredSlotIds: ['update-best'],
      semanticChecks: ['updateBest'],
    },
  },
  {
    id: 'string-length',
    kind: 'api',
    label: '字符串长度',
    worldMeaning: '告诉巡灯员字符轨道在什么位置结束。',
    canonicalCode: 's.length()',
    links: {
      sceneIds: ['character-track'],
      skillIds: ['scan'],
      traceFields: ['source'],
      referenceStepIds: ['scan-open'],
      mappingEntryIds: ['string-length'],
      structuredSlotIds: ['scan-condition'],
      semanticChecks: ['scan'],
    },
  },
  {
    id: 'string-char-at',
    kind: 'api',
    label: '按位置读取字符',
    worldMeaning: '从字符轨道的指定编号读取一个字符编码。',
    canonicalCode: 's.charAt(index)',
    links: {
      sceneIds: ['character-track'],
      skillIds: ['scan', 'shrink-duplicates'],
      traceFields: ['currentCode', 'changedCode'],
      referenceStepIds: ['read-current', 'release-left'],
      mappingEntryIds: ['string-char-at'],
      structuredSlotIds: ['read-current', 'release-left'],
      semanticChecks: ['readCurrent', 'release'],
    },
  },
  {
    id: 'array-access',
    kind: 'api',
    label: '频次数组访问',
    worldMeaning: '使用字符编码定位频次台中的对应格。',
    canonicalCode: 'counts[code]',
    links: {
      sceneIds: ['frequency-console'],
      skillIds: ['shrink-duplicates', 'admit-current'],
      traceFields: ['frequencies'],
      referenceStepIds: ['duplicate-open', 'release-left', 'admit-current'],
      mappingEntryIds: ['array-access'],
      structuredSlotIds: ['duplicate-condition', 'release-left', 'admit-current'],
      semanticChecks: ['duplicate', 'release', 'admit'],
    },
  },
  {
    id: 'method-result',
    kind: 'output',
    label: '返回最长长度',
    worldMeaning: '扫描结束后交付历史最长无重复窗口长度。',
    canonicalCode: 'return best',
    links: {
      sceneIds: ['best-readout'],
      skillIds: [],
      traceFields: ['bestLength'],
      referenceStepIds: ['return'],
      mappingEntryIds: ['result'],
      structuredSlotIds: ['result'],
      semanticChecks: ['return'],
    },
  },
]
