import type {
  CodeMappingEntry,
  LogicCodeStep,
  StructuredScaffold,
} from '../types'

export const LONGEST_SUBSTRING_SCAFFOLD: StructuredScaffold = {
  methodOpen: 'int lengthOfLongestSubstring(String s) {',
  methodClose: '}',
  slots: [
    {
      id: 'preparation',
      label: '准备窗口状态',
      responsibility: '让守窗员与巡灯员就位，建立左右边界、最长记录和 128 项字符频次数组。',
      lineCount: 4,
      conceptIds: ['left-boundary', 'right-boundary', 'best-length', 'frequency-table'],
    },
    {
      id: 'scan-condition',
      label: '扫描继续条件',
      responsibility: '巡灯员仍在字符串范围内时继续。',
      lineCount: 1,
      conceptIds: ['right-boundary', 'scan-boundary', 'string-length'],
    },
    {
      id: 'read-current',
      label: '读取当前字符',
      responsibility: '按巡灯员所在位置读取当前字符编码。',
      lineCount: 1,
      conceptIds: ['string-input', 'right-boundary', 'current-character', 'string-char-at'],
    },
    {
      id: 'duplicate-condition',
      label: '重复收缩条件',
      responsibility: '当前字符仍在窗口中时继续收缩。',
      lineCount: 1,
      conceptIds: ['current-character', 'frequency-table', 'duplicate-decision', 'array-access'],
    },
    {
      id: 'release-left',
      label: '移出左端字符',
      responsibility: '守窗员把左边界字符的窗口频次减一。',
      lineCount: 1,
      conceptIds: ['string-input', 'left-boundary', 'frequency-table', 'release-left-character', 'string-char-at', 'array-access'],
    },
    {
      id: 'advance-left',
      label: '守窗员推进左边界',
      responsibility: '左端字符移出后，守窗员带着窗口起点前进一步。',
      lineCount: 1,
      conceptIds: ['left-boundary', 'move-left-boundary'],
    },
    {
      id: 'admit-current',
      label: '纳入当前字符',
      responsibility: '重复清除后，把当前字符频次加一。',
      lineCount: 1,
      conceptIds: ['current-character', 'frequency-table', 'admit-current-character', 'array-access'],
    },
    {
      id: 'update-best',
      label: '更新最长记录',
      responsibility: '用当前窗口宽度更新历史最大值。',
      lineCount: 1,
      conceptIds: ['left-boundary', 'right-boundary', 'window-width', 'best-length'],
    },
    {
      id: 'advance-right',
      label: '巡灯员前进',
      responsibility: '本轮长度记录完成后，让巡灯员带着右边界前进一步。',
      lineCount: 1,
      conceptIds: ['right-boundary'],
    },
    {
      id: 'result',
      label: '返回最长长度',
      responsibility: '扫描结束后返回同一个最长记录变量。',
      lineCount: 1,
      conceptIds: ['best-length', 'method-result'],
    },
  ],
  body: [
    { kind: 'slot', depth: 1, slotId: 'preparation', suffix: ';' },
    {
      kind: 'composite',
      depth: 1,
      segments: [
        { kind: 'fixed', value: 'while (' },
        { kind: 'slot', slotId: 'scan-condition' },
        { kind: 'fixed', value: ') {' },
      ],
    },
    { kind: 'slot', depth: 2, slotId: 'read-current', suffix: ';' },
    {
      kind: 'composite',
      depth: 2,
      segments: [
        { kind: 'fixed', value: 'while (' },
        { kind: 'slot', slotId: 'duplicate-condition' },
        { kind: 'fixed', value: ') {' },
      ],
    },
    { kind: 'slot', depth: 2, slotId: 'release-left', suffix: ';' },
    { kind: 'slot', depth: 2, slotId: 'advance-left', suffix: ';' },
    { kind: 'fixed', depth: 2, value: '}' },
    { kind: 'slot', depth: 2, slotId: 'admit-current', suffix: ';' },
    { kind: 'slot', depth: 2, slotId: 'update-best', suffix: ';' },
    { kind: 'slot', depth: 2, slotId: 'advance-right', suffix: ';' },
    { kind: 'fixed', depth: 1, value: '}' },
    {
      kind: 'composite',
      depth: 1,
      segments: [
        { kind: 'fixed', value: 'return ' },
        { kind: 'slot', slotId: 'result' },
        { kind: 'fixed', value: ';' },
      ],
    },
  ],
}

export const LONGEST_SUBSTRING_REFERENCE_STEPS: LogicCodeStep[] = [
  {
    id: 'initialize', order: 1, stepLabel: '初始化灯廊',
    worldAction: '守窗员与巡灯员回到起点，清空频次台和最长记录。',
    logicPurpose: '建立滑动窗口需要的全部持久状态。', role: 'action', depth: 0, tone: 'yellow',
    code: `int left = 0;\nint right = 0;\nint best = 0;\nint[] counts = new int[128];`,
    semanticCheck: 'initialize',
    conceptIds: ['left-boundary', 'right-boundary', 'best-length', 'frequency-table'],
  },
  {
    id: 'scan-open', order: 2, stepLabel: '扫描直到末尾',
    worldAction: '巡灯员仍在字符轨道中，就开始新一轮。',
    logicPurpose: '用 while 逐字扩展窗口右侧。', role: 'open-scope', depth: 0, tone: 'ink',
    code: 'while (right < s.length()) {', semanticCheck: 'scan',
    conceptIds: ['right-boundary', 'scan-boundary', 'string-length'],
  },
  {
    id: 'read-current', order: 3, stepLabel: '读取当前字符',
    worldAction: '巡灯员用探照灯读取本轮准备纳入的字符。',
    logicPurpose: '保存字符编码，供重复判断和频次更新共同使用。', role: 'action', depth: 1, tone: 'steel',
    code: 'int current = s.charAt(right);', semanticCheck: 'readCurrent',
    conceptIds: ['string-input', 'right-boundary', 'current-character', 'string-char-at'],
  },
  {
    id: 'duplicate-open', order: 4, stepLabel: '重复时收缩',
    worldAction: '当前字符仍在窗口中，就从左侧继续缩短灯廊。',
    logicPurpose: '直到当前字符频次归零，恢复唯一性。', role: 'open-scope', depth: 1, tone: 'coral',
    code: 'while (counts[current] > 0) {', semanticCheck: 'duplicate',
    conceptIds: ['current-character', 'frequency-table', 'duplicate-decision', 'array-access'],
  },
  {
    id: 'release-left', order: 5, stepLabel: '移出左端字符',
    worldAction: '守窗员先撤销左端字符的窗口登记。',
    logicPurpose: '频次变化必须发生在左边界移动之前。', role: 'action', depth: 2, tone: 'coral',
    code: 'counts[s.charAt(left)]--;', semanticCheck: 'release',
    conceptIds: ['string-input', 'left-boundary', 'frequency-table', 'release-left-character', 'string-char-at', 'array-access'],
  },
  {
    id: 'advance-left', order: 6, stepLabel: '守窗员推进左边界',
    worldAction: '左端字符退出后，守窗员向右越过它。',
    logicPurpose: '缩小窗口并继续检查当前重复字符。', role: 'action', depth: 2, tone: 'steel',
    code: 'left++;', semanticCheck: 'moveLeft',
    conceptIds: ['left-boundary', 'move-left-boundary'],
  },
  {
    id: 'duplicate-close', order: 7, stepLabel: '重复清除',
    worldAction: '重复字符已经退出窗口，结束收缩。',
    logicPurpose: '闭合内部 while 的作用域。', role: 'close-scope', depth: 1, tone: 'coral',
    code: '}', semanticCheck: 'scopes',
    conceptIds: ['duplicate-decision'],
  },
  {
    id: 'admit-current', order: 8, stepLabel: '纳入当前字符',
    worldAction: '当前字符安全进入窗口，频次加一。',
    logicPurpose: '建立本轮无重复窗口。', role: 'action', depth: 1, tone: 'teal',
    code: 'counts[current]++;', semanticCheck: 'admit',
    conceptIds: ['current-character', 'frequency-table', 'admit-current-character', 'array-access'],
  },
  {
    id: 'update-best', order: 9, stepLabel: '更新最长记录',
    worldAction: '读取两个角色的位置，量出当前灯廊宽度。',
    logicPurpose: '编号差加一后，与历史最长值比较。', role: 'action', depth: 1, tone: 'yellow',
    code: 'best = Math.max(best, right - left + 1);', semanticCheck: 'updateBest',
    conceptIds: ['left-boundary', 'right-boundary', 'window-width', 'best-length'],
  },
  {
    id: 'advance-right', order: 10, stepLabel: '巡灯员前进',
    worldAction: '本轮记录完成，巡灯员进入下一个字符。',
    logicPurpose: '保证外层循环每轮前进一次。', role: 'action', depth: 1, tone: 'steel',
    code: 'right++;', semanticCheck: 'moveRight',
    conceptIds: ['right-boundary'],
  },
  {
    id: 'scan-close', order: 11, stepLabel: '结束扫描',
    worldAction: '巡灯员到达末尾，关闭扫描循环。',
    logicPurpose: '闭合外层 while 的作用域。', role: 'close-scope', depth: 0, tone: 'ink',
    code: '}', semanticCheck: 'scopes',
    conceptIds: ['scan-boundary'],
  },
  {
    id: 'return', order: 12, stepLabel: '交付最长记录',
    worldAction: '把灯廊保存的历史最长长度交付出去。',
    logicPurpose: '返回同一个最长记录变量。', role: 'result', depth: 0, tone: 'yellow',
    code: 'return best;', semanticCheck: 'return',
    conceptIds: ['best-length', 'method-result'],
  },
]

export const composeLongestSubstringReferenceBody = () =>
  LONGEST_SUBSTRING_REFERENCE_STEPS.map((step) => step.code).join('\n')

export const LONGEST_SUBSTRING_MAPPINGS: CodeMappingEntry[] = [
  { id: 'string-input', category: 'scene', label: '字符轨道', worldMeaning: '只读输入字符串，灯廊中的每一格对应一个字符位置。', code: 'String s', conceptIds: ['string-input'] },
  { id: 'left-boundary', category: 'scene', label: '守窗员 · 左边界', worldMeaning: '守住当前无重复窗口的起点，清退字符后向右收紧。', code: 'left', conceptIds: ['left-boundary'] },
  { id: 'right-boundary', category: 'scene', label: '巡灯员 · 右边界', worldMeaning: '用探照灯读取本轮字符，完成后向右巡查。', code: 'right', conceptIds: ['right-boundary'] },
  { id: 'current-character', category: 'scene', label: '巡灯员当前读数', worldMeaning: '巡灯员探照灯读取的 ASCII 字符编码。', code: 'current', conceptIds: ['current-character'] },
  { id: 'frequency-table', category: 'scene', label: '字符频次台', worldMeaning: '记录每个字符当前是否在窗口中。', code: 'int[] counts', conceptIds: ['frequency-table'] },
  { id: 'best-length', category: 'scene', label: '最长记录', worldMeaning: '历史上见过的最长无重复窗口长度。', code: 'best', conceptIds: ['best-length'] },
  { id: 'outer-while', category: 'syntax', label: '逐字巡灯', worldMeaning: '巡灯员尚未到达末尾时重复完整流程。', code: 'while (right < s.length())', conceptIds: ['scan-boundary'] },
  { id: 'duplicate-while', category: 'syntax', label: '重复时持续收缩', worldMeaning: '不是只移动一次，而是一直收缩到当前字符不再重复。', code: 'while (counts[current] > 0)', conceptIds: ['duplicate-decision'] },
  { id: 'release-left', category: 'skill', label: '移出左端字符', worldMeaning: '在左边界移动前先减少对应字符频次。', code: 'counts[s.charAt(left)]--', conceptIds: ['release-left-character'] },
  { id: 'advance-left', category: 'skill', label: '守窗员右移', worldMeaning: '守窗员越过刚刚移出的左端字符。', code: 'left++', conceptIds: ['move-left-boundary'] },
  { id: 'admit-current', category: 'skill', label: '纳入当前字符', worldMeaning: '当前字符不再重复后登记到窗口。', code: 'counts[current]++', conceptIds: ['admit-current-character'] },
  { id: 'window-width', category: 'skill', label: '计算窗口宽度', worldMeaning: '左右两端都包含在窗口中，因此编号差需要加一。', code: 'right - left + 1', conceptIds: ['window-width'] },
  { id: 'string-length', category: 'api', label: '字符串长度', worldMeaning: '确定扫描终止位置。', code: 's.length()', conceptIds: ['string-length'] },
  { id: 'string-char-at', category: 'api', label: '按位置读取字符', worldMeaning: '读取巡灯员或守窗员指向的字符。', code: 's.charAt(index)', conceptIds: ['string-char-at'] },
  { id: 'new-frequency-array', category: 'api', label: '新建频次数组', worldMeaning: '为 ASCII 字符创建 128 项、初值为 0 的计数表。', code: 'new int[128]', conceptIds: ['frequency-table'] },
  { id: 'array-access', category: 'api', label: '访问字符频次', worldMeaning: '使用字符编码定位计数表中的格子。', code: 'counts[code]', conceptIds: ['array-access'] },
  { id: 'math-max', category: 'api', label: '保留较大值', worldMeaning: '在历史最长和当前窗口宽度之间保留较大者。', code: 'Math.max(best, width)', conceptIds: ['best-length', 'window-width'] },
  { id: 'result', category: 'syntax', label: '返回最长长度', worldMeaning: '扫描结束后交付历史最长记录。', code: 'return best', conceptIds: ['method-result', 'best-length'] },
]
