import type { AlgorithmConceptDefinition } from '../types'

export const ARCHIVE_CONCEPTS: AlgorithmConceptDefinition[] = [
  {
    id: 'nums-input',
    kind: 'input',
    label: '数值带',
    worldMeaning: '依次经过的站点变化值，顺序不可打乱。',
    canonicalCode: 'nums[index]',
    lifecycle: {
      initialization: '由方法参数 nums 提供。',
      reads: ['逐项巡查读取当前站点。', '累加当前前缀时读取 nums[index]。'],
      writes: [],
      updateRule: '只读，不修改原数组。',
    },
    links: {
      sceneIds: ['archive-value-tape'],
      skillIds: ['scan-values', 'accumulate-prefix'],
      traceFields: ['values', 'currentValue'],
      referenceStepIds: ['scan-open', 'prefix-update'],
      mappingEntryIds: ['nums', 'array-access'],
      structuredSlotIds: ['loop-condition', 'prefix-update'],
      semanticChecks: ['scan', 'prefixUpdate'],
    },
  },
  {
    id: 'target-k',
    kind: 'input',
    label: '目标差值 K',
    worldMeaning: '任意两个前缀刻度之间需要达到的指定差值。',
    canonicalCode: 'k',
    lifecycle: {
      initialization: '由方法参数 k 提供。',
      reads: ['计算目标旧前缀时读取。'],
      writes: [],
      updateRule: '整次巡查保持不变。',
    },
    links: {
      sceneIds: ['archive-target-board'],
      skillIds: ['count-matches'],
      traceFields: ['target'],
      referenceStepIds: ['calculate-needed'],
      mappingEntryIds: ['target'],
      structuredSlotIds: ['needed'],
      semanticChecks: ['needed'],
    },
  },
  {
    id: 'scan-index',
    kind: 'state',
    label: '站点探针',
    worldMeaning: '指出本轮正在读取的数值带位置。',
    canonicalCode: 'index',
    lifecycle: {
      initialization: '从 0 号站开始。',
      reads: ['读取 nums[index]。', '判断是否到达 nums.length。'],
      writes: ['每轮完成全部档案动作后前进一格。'],
      updateRule: 'index++。',
    },
    links: {
      sceneIds: ['archive-index-probe'],
      skillIds: ['scan-values'],
      traceFields: ['currentIndex'],
      referenceStepIds: ['state-setup', 'scan-open', 'advance-index'],
      mappingEntryIds: ['index', 'array-length'],
      structuredSlotIds: ['state-setup', 'loop-condition', 'advance'],
      semanticChecks: ['state', 'scan', 'advance'],
    },
  },
  {
    id: 'current-prefix',
    kind: 'state',
    label: '累计刻度',
    worldMeaning: '从数值带起点到当前站的总变化。',
    canonicalCode: 'prefixSum',
    lifecycle: {
      initialization: '0。',
      reads: ['计算 needed。', '查询完成后作为新档案键。'],
      writes: ['进入每个站点后加上 nums[index]。'],
      updateRule: 'prefixSum += nums[index]。',
    },
    links: {
      sceneIds: ['archive-prefix-meter'],
      skillIds: ['initialize-archive', 'accumulate-prefix', 'count-matches', 'record-prefix'],
      traceFields: ['prefix'],
      referenceStepIds: ['state-setup', 'prefix-update', 'calculate-needed', 'record-prefix'],
      mappingEntryIds: ['prefix', 'prefix-update'],
      structuredSlotIds: ['state-setup', 'prefix-update', 'needed', 'record'],
      semanticChecks: ['state', 'prefixUpdate', 'needed', 'record'],
    },
  },
  {
    id: 'needed-prefix',
    kind: 'state',
    label: '目标旧刻度',
    worldMeaning: '当前刻度需要配对的历史前缀值。',
    canonicalCode: 'needed',
    lifecycle: {
      initialization: '每轮在当前前缀更新后产生。',
      reads: ['作为频次表查询键。'],
      writes: ['每轮写入 prefixSum - k。'],
      updateRule: 'needed = prefixSum - k。',
    },
    links: {
      sceneIds: ['archive-needed-window'],
      skillIds: ['count-matches'],
      traceFields: ['needed'],
      referenceStepIds: ['calculate-needed', 'count-matches'],
      mappingEntryIds: ['needed', 'difference'],
      structuredSlotIds: ['needed', 'count'],
      semanticChecks: ['needed', 'count'],
    },
  },
  {
    id: 'prefix-frequency',
    kind: 'state',
    label: '前缀档案柜',
    worldMeaning: '保存每种历史累计刻度已经出现多少次。',
    canonicalCode: 'frequency',
    lifecycle: {
      initialization: '空 HashMap 中先登记 0 -> 1。',
      reads: ['查询 needed 的历史次数。', '读取当前 prefixSum 的旧次数。'],
      writes: ['每轮查询结束后把当前 prefixSum 次数加一。'],
      updateRule: 'frequency.put(prefixSum, frequency.getOrDefault(prefixSum, 0) + 1)。',
    },
    links: {
      sceneIds: ['archive-frequency-cabinet'],
      skillIds: ['initialize-archive', 'count-matches', 'record-prefix'],
      traceFields: ['frequencyEntries', 'changedKey'],
      referenceStepIds: ['archive-setup', 'count-matches', 'record-prefix'],
      mappingEntryIds: ['frequency', 'new-hash-map', 'get-or-default', 'map-put'],
      structuredSlotIds: ['archive-setup', 'count', 'record'],
      semanticChecks: ['archive', 'count', 'record'],
    },
  },
  {
    id: 'answer-count',
    kind: 'output',
    label: '命中计数',
    worldMeaning: '已经找到的和为 K 的连续子数组总数。',
    canonicalCode: 'count',
    lifecycle: {
      initialization: '0。',
      reads: ['每轮累加旧前缀命中。', '巡查结束后返回。'],
      writes: ['加上 frequency.getOrDefault(needed, 0)。'],
      updateRule: 'count += matchedCount。',
    },
    links: {
      sceneIds: ['archive-answer-counter'],
      skillIds: ['initialize-archive', 'count-matches'],
      traceFields: ['answer', 'matchedCount'],
      referenceStepIds: ['state-setup', 'count-matches', 'return-result'],
      mappingEntryIds: ['count', 'return'],
      structuredSlotIds: ['state-setup', 'count', 'result'],
      semanticChecks: ['state', 'count', 'result'],
    },
  },
  {
    id: 'prefix-difference',
    kind: 'operation',
    label: '前缀差公式',
    worldMeaning: '用当前前缀减去目标 K，反推出需要的旧前缀。',
    canonicalCode: 'prefixSum - k',
    links: {
      sceneIds: ['archive-needed-formula'],
      skillIds: ['count-matches'],
      traceFields: ['prefix', 'target', 'needed'],
      referenceStepIds: ['calculate-needed'],
      mappingEntryIds: ['difference'],
      structuredSlotIds: ['needed'],
      semanticChecks: ['needed'],
    },
  },
  {
    id: 'frequency-lookup',
    kind: 'api',
    label: '安全查询历史次数',
    worldMeaning: '未出现的旧刻度按 0 次处理。',
    canonicalCode: 'frequency.getOrDefault(needed, 0)',
    links: {
      sceneIds: ['archive-frequency-cabinet'],
      skillIds: ['count-matches'],
      traceFields: ['matchedCount'],
      referenceStepIds: ['count-matches'],
      mappingEntryIds: ['get-or-default'],
      structuredSlotIds: ['count'],
      semanticChecks: ['count'],
    },
  },
  {
    id: 'frequency-record',
    kind: 'api',
    label: '登记当前前缀',
    worldMeaning: '把当前刻度作为后续站点可使用的历史起点。',
    canonicalCode: 'frequency.put(prefixSum, frequency.getOrDefault(prefixSum, 0) + 1)',
    links: {
      sceneIds: ['archive-frequency-cabinet'],
      skillIds: ['record-prefix'],
      traceFields: ['frequencyEntries', 'changedKey'],
      referenceStepIds: ['record-prefix'],
      mappingEntryIds: ['map-put'],
      structuredSlotIds: ['record'],
      semanticChecks: ['record'],
    },
  },
  {
    id: 'iteration-boundary',
    kind: 'boundary',
    label: '数值带末端',
    worldMeaning: '探针到达数组长度后结束巡查。',
    canonicalCode: 'index < nums.length',
    links: {
      sceneIds: ['archive-value-tape'],
      skillIds: ['scan-values'],
      traceFields: ['currentIndex'],
      referenceStepIds: ['scan-open', 'advance-index', 'scan-close'],
      mappingEntryIds: ['array-length', 'while-loop'],
      structuredSlotIds: ['loop-condition', 'advance'],
      semanticChecks: ['scan', 'advance', 'scope'],
    },
  },
  {
    id: 'method-result',
    kind: 'output',
    label: '返回命中总数',
    worldMeaning: '所有站点处理完后交付最终计数。',
    canonicalCode: 'return count',
    links: {
      sceneIds: ['archive-answer-counter'],
      skillIds: [],
      traceFields: ['answer'],
      referenceStepIds: ['return-result'],
      mappingEntryIds: ['return'],
      structuredSlotIds: ['result'],
      semanticChecks: ['result'],
    },
  },
]
