import type {
  CodeMappingEntry,
  LogicCodeStep,
  StructuredScaffold,
} from '../types'

export const ARCHIVE_REFERENCE_STEPS: LogicCodeStep[] = [
  {
    id: 'archive-setup', order: 1, stepLabel: '建立起点档案',
    worldAction: '开启档案柜并登记空前缀',
    logicPurpose: '创建频次表，并用 0 -> 1 覆盖从数组起点开始的目标区间。',
    role: 'action', depth: 0, tone: 'yellow', semanticCheck: 'archive',
    code: 'Map<Integer, Integer> frequency = new HashMap<>();\nfrequency.put(0, 1);',
    conceptIds: ['prefix-frequency'],
  },
  {
    id: 'state-setup', order: 2, stepLabel: '准备巡查状态',
    worldAction: '探针、累计刻度与命中计数归零',
    logicPurpose: '建立本轮遍历使用的三个持久状态。',
    role: 'action', depth: 0, tone: 'steel', semanticCheck: 'state',
    code: 'int index = 0;\nint prefixSum = 0;\nint needed = 0;\nint count = 0;',
    conceptIds: ['scan-index', 'current-prefix', 'needed-prefix', 'answer-count'],
  },
  {
    id: 'scan-open', order: 3, stepLabel: '逐项巡查',
    worldAction: '探针尚未到达数值带末端时继续',
    logicPurpose: '让同一套规则按顺序处理每个数组元素。',
    role: 'open-scope', depth: 0, tone: 'ink', semanticCheck: 'scan',
    code: 'while (index < nums.length) {',
    conceptIds: ['nums-input', 'scan-index', 'iteration-boundary'],
  },
  {
    id: 'prefix-update', order: 4, stepLabel: '累加当前刻度',
    worldAction: '把当前站值写入累计刻度',
    logicPurpose: '得到以当前位置为终点的当前前缀和。',
    role: 'action', depth: 1, tone: 'teal', semanticCheck: 'prefixUpdate',
    code: 'prefixSum += nums[index];',
    conceptIds: ['nums-input', 'scan-index', 'current-prefix'],
  },
  {
    id: 'calculate-needed', order: 5, stepLabel: '计算目标旧刻度',
    worldAction: '当前刻度减去目标差值 K',
    logicPurpose: '反推出能与当前位置组成目标子数组的历史前缀。',
    role: 'action', depth: 1, tone: 'steel', semanticCheck: 'needed',
    code: 'needed = prefixSum - k;',
    conceptIds: ['current-prefix', 'target-k', 'needed-prefix', 'prefix-difference'],
  },
  {
    id: 'count-matches', order: 6, stepLabel: '累加历史命中',
    worldAction: '调取旧刻度的全部档案章',
    logicPurpose: '每次历史出现都对应一个新的连续子数组。',
    role: 'action', depth: 1, tone: 'coral', semanticCheck: 'count',
    code: 'count += frequency.getOrDefault(needed, 0);',
    conceptIds: ['needed-prefix', 'prefix-frequency', 'frequency-lookup', 'answer-count'],
  },
  {
    id: 'record-prefix', order: 7, stepLabel: '登记当前刻度',
    worldAction: '查询完成后给当前刻度加一枚章',
    logicPurpose: '把当前前缀留给后续位置使用，并避免把空区间算作答案。',
    role: 'action', depth: 1, tone: 'teal', semanticCheck: 'record',
    code: 'frequency.put(prefixSum, frequency.getOrDefault(prefixSum, 0) + 1);',
    conceptIds: ['current-prefix', 'prefix-frequency', 'frequency-record'],
  },
  {
    id: 'advance-index', order: 8, stepLabel: '探针前进',
    worldAction: '本轮写回后进入下一站',
    logicPurpose: '保证循环有序前进并最终终止。',
    role: 'action', depth: 1, tone: 'steel', semanticCheck: 'advance',
    code: 'index++;',
    conceptIds: ['scan-index', 'iteration-boundary'],
  },
  {
    id: 'scan-close', order: 9, stepLabel: '结束巡查作用域',
    worldAction: '探针到达末端，关闭数值带',
    logicPurpose: '结束 while 内每轮动作的作用域。',
    role: 'close-scope', depth: 0, tone: 'ink', semanticCheck: 'scope',
    code: '}',
    conceptIds: ['iteration-boundary'],
  },
  {
    id: 'return-result', order: 10, stepLabel: '交付命中计数',
    worldAction: '读取最终计数器',
    logicPurpose: '返回所有和为 K 的连续子数组数量。',
    role: 'result', depth: 0, tone: 'yellow', semanticCheck: 'result',
    code: 'return count;',
    conceptIds: ['answer-count', 'method-result'],
  },
]

export const ARCHIVE_MAPPINGS: CodeMappingEntry[] = [
  { id: 'nums', category: 'scene', label: '数值带', worldMeaning: '输入数组与当前站点值。', code: 'nums / nums[index]', conceptIds: ['nums-input'] },
  { id: 'target', category: 'scene', label: '目标差值牌', worldMeaning: '希望连续区间达到的总和。', code: 'k', conceptIds: ['target-k'] },
  { id: 'index', category: 'scene', label: '站点探针', worldMeaning: '当前正在处理的数组位置。', code: 'index', conceptIds: ['scan-index'] },
  { id: 'prefix', category: 'scene', label: '累计刻度', worldMeaning: '从起点到当前站的前缀和。', code: 'prefixSum', conceptIds: ['current-prefix'] },
  { id: 'needed', category: 'scene', label: '目标旧刻度', worldMeaning: '需要在历史档案中匹配的前缀和。', code: 'needed', conceptIds: ['needed-prefix'] },
  { id: 'frequency', category: 'scene', label: '前缀档案柜', worldMeaning: '每种历史前缀和的出现次数。', code: 'frequency', conceptIds: ['prefix-frequency'] },
  { id: 'count', category: 'scene', label: '命中计数器', worldMeaning: '已经确认的目标子数组总数。', code: 'count', conceptIds: ['answer-count'] },
  { id: 'prefix-update', category: 'skill', label: '累加当前刻度', worldMeaning: '先把当前元素纳入前缀和。', code: 'prefixSum += nums[index]', conceptIds: ['nums-input', 'scan-index', 'current-prefix'] },
  { id: 'difference', category: 'skill', label: '计算目标旧刻度', worldMeaning: '当前前缀减 K，得到应查询的旧前缀。', code: 'prefixSum - k', conceptIds: ['prefix-difference', 'needed-prefix'] },
  { id: 'while-loop', category: 'syntax', label: '持续巡查', worldMeaning: '探针未到末端时重复执行作用域内动作。', code: 'while (index < nums.length) { ... }', conceptIds: ['iteration-boundary', 'scan-index'] },
  { id: 'return', category: 'syntax', label: '返回命中总数', worldMeaning: '遍历结束后返回累计结果。', code: 'return count', conceptIds: ['answer-count', 'method-result'] },
  { id: 'new-hash-map', category: 'api', label: '新建整数档案柜', worldMeaning: '创建前缀和到出现次数的映射。', code: 'new HashMap<>()', conceptIds: ['prefix-frequency'] },
  { id: 'get-or-default', category: 'api', label: '安全查询次数', worldMeaning: '不存在的前缀和按 0 次处理。', code: 'frequency.getOrDefault(key, 0)', conceptIds: ['prefix-frequency', 'frequency-lookup'] },
  { id: 'map-put', category: 'api', label: '写入档案次数', worldMeaning: '保存某个前缀和最新的出现次数。', code: 'frequency.put(key, count)', conceptIds: ['prefix-frequency', 'frequency-record'] },
  { id: 'array-access', category: 'api', label: '读取当前站值', worldMeaning: '用探针下标读取数组元素。', code: 'nums[index]', conceptIds: ['nums-input', 'scan-index'] },
  { id: 'array-length', category: 'api', label: '读取数值带长度', worldMeaning: '确定巡查停止边界。', code: 'nums.length', conceptIds: ['iteration-boundary'] },
]

export const ARCHIVE_SCAFFOLD: StructuredScaffold = {
  methodOpen: 'public int subarraySum(int[] nums, int k) {',
  methodClose: '}',
  slots: [
    { id: 'archive-setup', label: '起点档案', responsibility: '创建整数 Map，并登记空前缀 0 -> 1。', lineCount: 2, conceptIds: ['prefix-frequency'] },
    { id: 'state-setup', label: '巡查状态', responsibility: '初始化站点探针、累计刻度、目标旧刻度和命中计数。', lineCount: 4, conceptIds: ['scan-index', 'current-prefix', 'needed-prefix', 'answer-count'] },
    { id: 'loop-condition', label: '巡查条件', responsibility: '探针未到 nums.length 时继续。', lineCount: 1, conceptIds: ['scan-index', 'iteration-boundary'] },
    { id: 'prefix-update', label: '累计刻度', responsibility: '把 nums[index] 加到当前前缀和。', lineCount: 1, conceptIds: ['nums-input', 'scan-index', 'current-prefix'] },
    { id: 'needed', label: '目标旧刻度', responsibility: '计算当前前缀减 k。', lineCount: 1, conceptIds: ['target-k', 'current-prefix', 'needed-prefix', 'prefix-difference'] },
    { id: 'count', label: '累加命中', responsibility: '查询 needed 的历史次数并累加答案。', lineCount: 1, conceptIds: ['needed-prefix', 'prefix-frequency', 'frequency-lookup', 'answer-count'] },
    { id: 'record', label: '登记当前刻度', responsibility: '查询之后把当前前缀的次数增加一。', lineCount: 1, conceptIds: ['current-prefix', 'prefix-frequency', 'frequency-record'] },
    { id: 'advance', label: '探针前进', responsibility: '本轮结束后让 index 前进一格。', lineCount: 1, conceptIds: ['scan-index', 'iteration-boundary'] },
    { id: 'result', label: '返回结果', responsibility: '遍历结束后返回命中计数。', lineCount: 1, conceptIds: ['answer-count', 'method-result'] },
  ],
  body: [
    { kind: 'slot', depth: 0, slotId: 'archive-setup', suffix: ';' },
    { kind: 'slot', depth: 0, slotId: 'state-setup', suffix: ';' },
    {
      kind: 'composite', depth: 0,
      segments: [
        { kind: 'fixed', value: 'while (' },
        { kind: 'slot', slotId: 'loop-condition' },
        { kind: 'fixed', value: ') {' },
      ],
    },
    { kind: 'slot', depth: 1, slotId: 'prefix-update', suffix: ';' },
    { kind: 'slot', depth: 1, slotId: 'needed', suffix: ';' },
    { kind: 'slot', depth: 1, slotId: 'count', suffix: ';' },
    { kind: 'slot', depth: 1, slotId: 'record', suffix: ';' },
    { kind: 'slot', depth: 1, slotId: 'advance', suffix: ';' },
    { kind: 'fixed', depth: 0, value: '}' },
    { kind: 'slot', depth: 0, slotId: 'result', suffix: ';' },
  ],
}
